import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const uri=s=>'data:text/javascript;base64,'+Buffer.from(compile(s)).toString('base64');
const optionURL=uri(readFileSync(new URL('../lib/intake-options.ts',import.meta.url),'utf8'));
const source=readFileSync(new URL('../app/api/intake/route.ts',import.meta.url),'utf8').replace('import {NextResponse} from "next/server";', 'const NextResponse={json:(b,i)=>Response.json(b,i)};').replace('import {requireOperationalContext,operationalRole,clinicalRole} from "@/lib/server-access";', 'const requireOperationalContext=()=>globalThis.__ctx;const operationalRole=r=>r.includes("reception");const clinicalRole=r=>r.includes("doctor");').replace('"@/lib/intake-options"',JSON.stringify(optionURL));
const api=await import(uri(source));const {validateIntake,intakeOptions}=await import(optionURL);
function setup(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(`CREATE TABLE patients(id TEXT PRIMARY KEY,tenant_id TEXT,clinic_id TEXT,archived_at TEXT); INSERT INTO patients VALUES('p','t','c',NULL),('foreign','other','c',NULL);CREATE TABLE audit_logs(id TEXT,tenant_id TEXT,actor_id TEXT,entity_type TEXT,entity_id TEXT,action TEXT,occurred_at TEXT,created_at TEXT,updated_at TEXT);`);sqlite.exec(readFileSync(new URL('../db/intake-assessment.sql',import.meta.url),'utf8'));
const prepare=sql=>{let args=[];const q={bind(...a){args=a.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v);return q;},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args).map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,v instanceof Uint8Array?Array.from(v):v]))) };},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};return q;};
globalThis.__ctx={db:{prepare,async batch(s){sqlite.exec('BEGIN');try{const out=[];for(const x of s)out.push(await x.run());sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}},tenantId:'t',clinicId:'c',user:{id:'u'},roles:['reception']};return sqlite;}
const get=(id='p',doc='')=>new Request('http://local/api/intake?patientId='+id+(doc?'&documentId='+doc:''));
const post=body=>new Request(get(),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const upload=bytes=>{const f=new FormData();f.set('file',new File([bytes],'baseline.png',{type:'image/png'}));f.set('kind','image');f.set('view','أمامية / Front');return new Request(get(),{method:'POST',body:f});};
test('durable save, concurrency, consent, upload roundtrip and access isolation',async()=>{const db=setup();assert.equal((await api.GET(get('foreign'))).status,404);const data={email:'test@example.com',birthDate:'1990-05-06',goal:intakeOptions.goal[0],consent:'no'};
assert.equal((await api.POST(post({data,version:0}))).status,200);assert.equal((await api.POST(post({data,version:0}))).status,409);const bytes=new Uint8Array(600000);bytes.set([137,80,78,71,13,10,26,10]);assert.equal((await api.POST(upload(bytes))).status,409);assert.equal((await api.POST(post({data:{...data,consent:'yes'},version:1}))).status,200);assert.equal((await api.POST(upload(new Uint8Array([1,2,3])))).status,400);assert.equal((await api.POST(upload(bytes))).status,200);
const saved=await (await api.GET(get())).json();assert.equal(saved.data.email,data.email);assert.equal(saved.documents.length,1);const r=await api.GET(get('p',saved.documents[0].id));assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);assert.equal(r.headers.get('Cache-Control'),'private, no-store');globalThis.__ctx.roles=['doctor'];assert.equal((await api.GET(get())).status,200);assert.equal((await api.POST(post({data,version:2}))).status,403);globalThis.__ctx.roles=['patient'];assert.equal((await api.GET(get())).status,403);globalThis.__ctx={error:'AUTHENTICATION_REQUIRED',status:401};assert.equal((await api.GET(get())).status,401);db.close();});
test('allowlists and dates',()=>{assert.equal(validateIntake({goal:'invented'}),false);assert.equal(validateIntake({email:'invalid'}),false);assert.equal(validateIntake({travelYear:'2026',travelMonth:'2',travelDay:'31'}),false);assert.equal(validateIntake({consent:'yes',medicationTypes:[intakeOptions.medicationTypes[0]]}),true);assert.equal(validateIntake({arbitrary:'field'}),false);});
