import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';
const uri=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');
const skinURL=uri(readFileSync('lib/skin-assessment.ts','utf8'));const skin=await import(skinURL);
const src=readFileSync('lib/skin-ai-service.ts','utf8').replace("import {NextResponse} from 'next/server';","const NextResponse={json:(b,i)=>Response.json(b,i)};").replace("import {requireOperationalContext,operationalRole,clinicalRole} from '@/lib/server-access';","const requireOperationalContext=()=>globalThis.ctx;const operationalRole=r=>r.includes('reception');const clinicalRole=r=>r.includes('doctor');").replace("'@/lib/skin-assessment'",JSON.stringify(skinURL)).replace("const {env}=await import('cloudflare:workers');","const env=globalThis.env;");const api=await import(uri(src));
const draft=()=>({summary:'Visible observations',limitations:'One view',reviewPoints:'Examination needed',parameters:Array.from({length:36},(_,i)=>({id:i+1,grade:i<2?2:null,observation:'Test',sourceImages:[]}))});
function setup(){const s=new DatabaseSync(':memory:');s.exec(`CREATE TABLE patients(id TEXT PRIMARY KEY,tenant_id TEXT,clinic_id TEXT,archived_at TEXT);INSERT INTO patients VALUES('p','t','c',NULL),('foreign','x','c',NULL);CREATE TABLE role_assignments(user_id TEXT,tenant_id TEXT,clinic_id TEXT,status TEXT,role TEXT);INSERT INTO role_assignments VALUES('u','t','c','active','reception'),('u','t','other','active','doctor');CREATE TABLE audit_logs(id TEXT,tenant_id TEXT,actor_id TEXT,entity_type TEXT,entity_id TEXT,action TEXT,occurred_at TEXT,created_at TEXT,updated_at TEXT);`);s.exec(readFileSync('db/intake-assessment.sql','utf8'));
s.prepare('INSERT INTO intake_documents VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('image','p','t','c','image','Front','private-name.png','image/png',8,'now','u');s.prepare('INSERT INTO intake_document_chunks VALUES(?,?,?)').run('image',0,new Uint8Array([137,80,78,71,13,10,26,10]));
const prepare=sql=>{let args=[];const q={bind(...a){args=a;return q},async first(){return s.prepare(sql).get(...args)||null},async all(){return {results:s.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(s.prepare(sql).run(...args).changes)}}}};return q};globalThis.ctx={db:{prepare,async batch(q){s.exec('BEGIN');try{const r=[];for(const x of q)r.push(await x.run());s.exec('COMMIT');return r}catch(e){s.exec('ROLLBACK');throw e}}},tenantId:'t',clinicId:'c',user:{id:'u'},roles:['doctor','reception']};globalThis.env={OPENAI_API_KEY:'test-only-key'};return s;}
const get=(p='p')=>new Request('https://local/api/intake/ai?patientId='+p);
const post=(body,p='p',origin='https://local')=>new Request(get(p),{method:'POST',headers:{origin},body:JSON.stringify(body)});
const generate={action:'generate',documentId:'image',language:'en',consent:true};
function consent(s){s.prepare('INSERT INTO intake_assessments(patient_id,tenant_id,clinic_id,data_json,version,updated_at,updated_by) VALUES(?,?,?,?,?,?,?)').run('p','t','c',JSON.stringify({consent:'yes',email:'never-send@example.com'}),1,'now','u');}
test('36 grades validated; missing, duplicate, malformed and out-of-range rejected; N/A excluded',()=>{const r=draft();assert(skin.validSkinDraft(r));assert.deepEqual(skin.descriptiveAverage(r),{count:2,sum:4,mean:2,normalized:50});for(const change of [x=>x.parameters[0]=null,x=>x.parameters[0].grade=5,x=>x.parameters[0].id=2,x=>x.parameters.pop(),x=>x.parameters[35].grade=0]){const x=draft();change(x);assert.equal(skin.validSkinDraft(x),false)}});
test('consent, scoped roles, paid-request protection, stored report and physician comments',async()=>{const s=setup();let calls=0;const old=globalThis.fetch;globalThis.fetch=async(url,opts)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const b=JSON.parse(opts.body);assert.equal(b.store,false);assert.equal(opts.headers.Authorization,'Bearer test-only-key');assert.equal(b.text.format.strict,true);assert(!opts.body.includes('never-send'));assert(!opts.body.includes('private-name'));return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(draft())}]}]})};try{
assert.equal((await api.GET(get('foreign'))).status,404);assert.equal((await (await api.GET(get())).json()).canComment,false);assert.equal((await api.POST(post({...generate,consent:false}))).status,400);assert.equal((await api.POST(post(generate,'p','https://other'))).status,403);assert.equal((await api.POST(post(generate))).status,409);assert.equal(calls,0);consent(s);assert.equal((await api.POST(post(generate))).status,200);assert.equal(calls,1);assert.equal((await api.POST(post(generate))).status,429);assert.equal(calls,1);const response=await api.GET(get());assert.equal(response.headers.get('cache-control'),'no-store');const body=await response.json();assert.equal(body.reports[0].status,'completed');assert(!JSON.stringify(body).includes('test-only-key'));const comment={action:'comment',reportId:body.reports[0].id,comment:'Reviewed in clinic'};assert.equal((await api.POST(post(comment))).status,403);s.exec("UPDATE role_assignments SET role='doctor' WHERE clinic_id='c'");assert.equal((await api.POST(post(comment))).status,200);assert.equal((await (await api.GET(get())).json()).reports[0].comments.length,1);assert.equal(s.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,3);
}finally{globalThis.fetch=old;s.close()}});
test('upstream errors sanitized and failures retained without retry',async()=>{const s=setup();consent(s);const old=globalThis.fetch;globalThis.fetch=async()=>new Response('secret upstream text',{status:429});try{const r=await api.POST(post(generate));assert.equal(r.status,502);assert.deepEqual(await r.json(),{error:'OPENAI_QUOTA_OR_RATE_LIMIT'});assert.equal(s.prepare('SELECT status FROM skin_ai_reports').get().status,'failed')}finally{globalThis.fetch=old;s.close()}});

test('multi-image request uses all scoped sources and persists labels; invalid sets do not call OpenAI',async()=>{const s=setup();consent(s);s.prepare('INSERT INTO intake_documents VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('second','p','t','c','image','Side','second.png','image/png',8,'now','u');s.prepare('INSERT INTO intake_document_chunks VALUES(?,?,?)').run('second',0,new Uint8Array([137,80,78,71,13,10,26,10]));const old=globalThis.fetch;let calls=0;globalThis.fetch=async(url,o)=>{calls++;const body=JSON.parse(o.body);assert.equal(body.input[0].content.filter(x=>x.type==='input_image').length,2);const r=draft();r.parameters[0].sourceImages=[1,2];return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(r)}]}]})};try{const one={id:'image',angle:'Front',mode:'Daylight'},two={id:'second',angle:'Left oblique',mode:'Unknown'};for(const images of [[],[one,one],Array(31).fill(one),[{...one,mode:'invented'}]])assert.equal((await api.POST(post({...generate,images}))).status,400);assert.equal((await api.POST(post({...generate,images:[one,{...two,id:'missing'}]}))).status,404);s.exec("UPDATE intake_documents SET size=9000000 WHERE id='second'");assert.equal((await api.POST(post({...generate,images:[one,two]}))).status,413);assert.equal(calls,0);s.exec("UPDATE intake_documents SET size=8 WHERE id='second'");assert.equal((await api.POST(post({...generate,images:[one,two]}))).status,200);const saved=await (await api.GET(get())).json();assert.deepEqual(saved.reports[0].report.sources,[one,two]);assert.deepEqual(saved.reports[0].report.parameters[0].sourceImages,[1,2]);assert.equal(calls,1)}finally{globalThis.fetch=old;s.close()}});

const patientSrc=readFileSync('app/api/patient/skin/route.ts','utf8').replace("import {NextResponse} from 'next/server';","const NextResponse={json:(b,i)=>Response.json(b,i)};").replace("import {requireOperationalContext,clinicalRole} from '@/lib/server-access';","const requireOperationalContext=()=>globalThis.ctx;const clinicalRole=r=>r.includes('doctor');").replace("import {POST as generateReport} from '@/lib/skin-ai-service';",`import {POST as generateReport} from ${JSON.stringify(uri(src))};`).replace("const {env}=await import('cloudflare:workers');","const env=globalThis.env;");
const patientApi=await import(uri(patientSrc));
const homeRequest=(body,p='p')=>new Request('https://local/api/patient/skin?patientId='+p,{method:body?'POST':'GET',...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});
const homeUpload=(consented=true,bytes=new Uint8Array([137,80,78,71,13,10,26,10]))=>{const f=new FormData();if(consented)f.set('consent','yes');for(let i=0;i<3;i++)f.append('images',new File([bytes],i+'.png',{type:'image/png'}));return f;};
function homeSetup(){const s=setup();s.exec("ALTER TABLE patients ADD COLUMN profile_id TEXT;UPDATE patients SET profile_id='u' WHERE id='p';UPDATE patients SET profile_id='other' WHERE id='foreign';");
 // Match D1's ArrayBuffer binding support for document chunks.
 const original=globalThis.ctx.db.prepare;globalThis.ctx.db.prepare=sql=>{const q=original(sql);const bind=q.bind;q.bind=(...a)=>bind(...a.map(x=>x instanceof ArrayBuffer?new Uint8Array(x):x));return q;};return s;}
test('patient home capture: owned files, explicit consents, all three views, baseline remains first clinic report',async()=>{const s=homeSetup();consent(s);const old=globalThis.fetch;let calls=0;globalThis.fetch=async(url,o)=>{calls++;const b=JSON.parse(o.body);if(calls>1){assert.equal(b.input[0].content.filter(x=>x.type==='input_image').length,3);assert(b.instructions.includes('NOT OBSERV'));assert(!o.body.includes('never-send'));}return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(draft())}]}]})};try{
 assert.equal((await api.POST(post(generate))).status,200);const baseline=s.prepare('SELECT id FROM skin_ai_reports').get().id;s.exec("UPDATE skin_ai_reports SET created_at='2026-01-01T00:00:00Z'");
 s.exec("UPDATE role_assignments SET role='patient' WHERE clinic_id='c'");globalThis.ctx.roles=['patient'];
 assert.equal((await patientApi.POST(homeRequest(homeUpload(false)))).status,400);assert.equal((await patientApi.POST(homeRequest(homeUpload(true,new Uint8Array([1,2,3]))))).status,400);
 assert.equal((await patientApi.POST(homeRequest(homeUpload(),'foreign'))).status,403);
 const upload=await patientApi.POST(homeRequest(homeUpload()));assert.equal(upload.status,200,await upload.clone().text());const {sessionId}=await upload.json();let data=await (await patientApi.GET(homeRequest())).json();assert.equal(data.baseline.id,baseline);assert.equal(data.registrationSnapshot,true);assert.equal(data.sessions[0].images.length,3);assert.equal(data.preview,false);
 const id=data.sessions[0].images[0].id;const r=await patientApi.GET(new Request('https://local/api/patient/skin?patientId=p&documentId='+id));assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,8);assert.equal(r.headers.get('cache-control'),'private, no-store');
 assert.equal((await patientApi.POST(homeRequest({action:'generate',sessionId,language:'en',consent:false}))).status,400);
 assert.equal((await patientApi.POST(homeRequest({action:'generate',sessionId:'not-owned',language:'en',consent:true}))).status,404);
 const generated=await patientApi.POST(homeRequest({action:'generate',sessionId,language:'en',consent:true}));assert.equal(generated.status,200,await generated.clone().text());assert.equal(calls,2);
 data=await (await patientApi.GET(homeRequest())).json();assert.equal(data.baseline.id,baseline);assert.equal(data.homeReports.length,1);assert.equal(data.homeReports[0].report.captureSource,'home-smartphone');assert.equal(data.homeReports[0].report.intakeSnapshot,undefined);
 assert.equal((await patientApi.POST(homeRequest({action:'comment',reportId:baseline,comment:'x'}))).status,400);
 assert.equal((await patientApi.POST(homeRequest(homeUpload()))).status,200);assert.equal((await patientApi.POST(homeRequest(homeUpload()))).status,200);assert.equal((await patientApi.POST(homeRequest(homeUpload()))).status,429);assert.equal(s.prepare("SELECT COUNT(*) n FROM intake_documents WHERE kind='home_image'").get().n,9);
 }finally{globalThis.fetch=old;s.close()}});
test('patient reads deny unlinked identities and cross-clinic roles; staff preview is read-only',async()=>{const s=homeSetup();consent(s);try{
 s.exec("UPDATE patients SET profile_id='another' WHERE id='p'");globalThis.ctx.roles=['doctor'];
 // The only doctor assignment is in another clinic, so aggregated roles do not grant access.
 assert.equal((await patientApi.GET(homeRequest())).status,403);assert.equal((await patientApi.POST(homeRequest(homeUpload()))).status,403);
 s.exec("UPDATE role_assignments SET role='doctor' WHERE clinic_id='c'");const r=await patientApi.GET(homeRequest());assert.equal(r.status,200);assert.equal((await r.json()).preview,true);assert.equal((await patientApi.POST(homeRequest(homeUpload()))).status,403);
 assert.equal((await patientApi.GET(homeRequest(null,'foreign'))).status,404);
 globalThis.ctx={error:'AUTHENTICATION_REQUIRED',status:401};assert.equal((await patientApi.GET(homeRequest())).status,401);
 }finally{s.close()}});
