import {NextResponse} from "next/server";
import {operationalRole,requireOperationalContext} from "@/lib/server-access";
export const dynamic="force-dynamic";
export async function GET(){const ctx=await requireOperationalContext();if("error" in ctx)return NextResponse.json({error:ctx.error},{status:ctx.status});if(!operationalRole(ctx.roles))return NextResponse.json({error:"FORBIDDEN"},{status:403});const {db,tenantId,clinicId}=ctx;
 const now=new Date().toISOString();await db.batch([
  db.prepare("INSERT OR IGNORE INTO communication_templates (id,tenant_id,key,name_ar,name_en,body_ar,body_en,category,status,version,approved_by,approved_at,created_at,updated_at) VALUES (?,?, 'appointment_24h','تذكير الموعد','Appointment reminder','تذكير: لديك موعد قادم في Derma Glow.','Reminder: you have an upcoming Derma Glow appointment.','appointment','approved',1,?,?,?,?)").bind(`${tenantId}:tpl:appointment_24h`,tenantId,ctx.user.id,now,now,now),
  db.prepare("INSERT OR IGNORE INTO communication_templates (id,tenant_id,key,name_ar,name_en,body_ar,body_en,category,status,version,approved_by,approved_at,created_at,updated_at) VALUES (?,?, 'post_session_t1','متابعة اليوم التالي','Next-day follow-up','كيف تشعر بشرتك اليوم بعد الجلسة؟','How is your skin today after the session?','follow_up','approved',1,?,?,?,?)").bind(`${tenantId}:tpl:post_session_t1`,tenantId,ctx.user.id,now,now,now),
  db.prepare("INSERT OR IGNORE INTO communication_templates (id,tenant_id,key,name_ar,name_en,body_ar,body_en,category,status,version,approved_by,approved_at,created_at,updated_at) VALUES (?,?, 'missed_routine','متابعة الروتين','Routine follow-up','لاحظنا أن خطوة من الروتين لم تُسجل. هل تحتاج مساعدة؟','A routine step was not recorded. Do you need help?','adherence','approved',1,?,?,?,?)").bind(`${tenantId}:tpl:missed_routine`,tenantId,ctx.user.id,now,now,now),
  ...[["appointment_24h","تذكير الموعد قبل 24 ساعة","24-hour appointment reminder","time","appointment_24h",0],["post_session_t1","متابعة اليوم التالي للجلسة","Next-day post-session follow-up","time","post_session_t1",1],["missed_routine","متابعة الروتين غير المسجل","Missed routine follow-up","event","missed_routine",0]].map(([key,ar,en,trigger,template,clinical])=>db.prepare("INSERT OR IGNORE INTO automation_rules (id,tenant_id,key,name_ar,name_en,trigger_type,channel,template_key,enabled,requires_clinical_approval,created_at,updated_at) VALUES (?,?,?,?,?,?,'in_app',?,1,?,?,?)").bind(`${tenantId}:rule:${key}`,tenantId,key,ar,en,trigger,template,clinical,now,now))
 ]);
 const [threads,messages,outbox,templates,rules,tasks]=await Promise.all([
  db.prepare("SELECT mt.*,p.reference_code,pp.full_name_ar,pp.full_name_en,(SELECT COUNT(*) FROM patient_messages pm WHERE pm.thread_id=mt.id AND pm.sender_role='patient' AND pm.read_at IS NULL) unread_count FROM message_threads mt JOIN patients p ON p.id=mt.patient_id LEFT JOIN patient_profiles pp ON pp.patient_id=p.id WHERE mt.tenant_id=? AND p.clinic_id=? ORDER BY mt.last_message_at DESC").bind(tenantId,clinicId).all(),
  db.prepare("SELECT * FROM patient_messages WHERE tenant_id=? ORDER BY sent_at").bind(tenantId).all(),
  db.prepare("SELECT no.*,p.reference_code,pp.full_name_ar,pp.full_name_en FROM notification_outbox no JOIN patients p ON p.id=no.patient_id LEFT JOIN patient_profiles pp ON pp.patient_id=p.id WHERE no.tenant_id=? ORDER BY no.scheduled_for DESC LIMIT 100").bind(tenantId).all(),
  db.prepare("SELECT * FROM communication_templates WHERE tenant_id=? ORDER BY category,key,version DESC").bind(tenantId).all(),
  db.prepare("SELECT * FROM automation_rules WHERE tenant_id=? ORDER BY key").bind(tenantId).all(),
  db.prepare("SELECT ct.*,p.reference_code,pp.full_name_ar,pp.full_name_en FROM care_tasks ct JOIN patients p ON p.id=ct.patient_id LEFT JOIN patient_profiles pp ON pp.patient_id=p.id WHERE ct.tenant_id=? AND ct.status='open' ORDER BY CASE ct.priority WHEN 'high' THEN 1 ELSE 2 END,ct.due_at").bind(tenantId).all()
 ]);return NextResponse.json({threads:threads.results,messages:messages.results,outbox:outbox.results,templates:templates.results,rules:rules.results,tasks:tasks.results});}
