import {NextResponse} from "next/server";
import {clinicalRole,medicalDirectorRole,requireOperationalContext} from "@/lib/server-access";
import {transitionJourney} from "@/lib/journey-engine.mjs";
import {validateConsultation,validateDailyDecision,validateSession} from "@/lib/clinical-workflow.mjs";
export const dynamic="force-dynamic";
type Body={action:string;[key:string]:unknown};

export async function POST(request:Request){
 const ctx=await requireOperationalContext();if("error" in ctx)return NextResponse.json({error:ctx.error},{status:ctx.status});if(!clinicalRole(ctx.roles))return NextResponse.json({error:"FORBIDDEN"},{status:403});
 const body=await request.json().catch(()=>null) as Body|null;if(!body?.action)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});
 const {db,tenantId,clinicId,user}=ctx,now=new Date().toISOString(),patientId=String(body.patientId??""),journeyId=String(body.journeyId??"");
 const patient=patientId?await db.prepare("SELECT id FROM patients WHERE id=? AND tenant_id=? AND clinic_id=?").bind(patientId,tenantId,clinicId).first():null;if(body.action!=="template_approve"&&!patient)return NextResponse.json({error:"PATIENT_NOT_FOUND"},{status:404});
 try{
  if(body.action==="consultation_save"||body.action==="consultation_approve_close"){
   validateConsultation(body);const existing=await db.prepare("SELECT id FROM consultations WHERE patient_id=? AND journey_id=? ORDER BY created_at DESC LIMIT 1").bind(patientId,journeyId).first<{id:string}>();const consultationId=existing?.id||crypto.randomUUID(),status=body.action==="consultation_approve_close"?"approved":"draft";
   if(existing)await db.prepare("UPDATE consultations SET severity=?,clinical_conclusion=?,target_outcome=?,routine_json=?,medication_json=?,instructions_json=?,status=?,physician_id=?,approved_at=?,closed_at=?,updated_at=? WHERE id=?").bind(body.severity,body.clinicalConclusion,body.targetOutcome,JSON.stringify({text:body.routine}),JSON.stringify({text:body.medication||""}),JSON.stringify({text:body.instructions||""}),status,user.id,status==="approved"?now:null,status==="approved"?now:null,now,consultationId).run();
   else await db.prepare("INSERT INTO consultations (id,tenant_id,clinic_id,patient_id,journey_id,physician_id,severity,clinical_conclusion,target_outcome,routine_json,medication_json,instructions_json,status,approved_at,closed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(consultationId,tenantId,clinicId,patientId,journeyId,user.id,body.severity,body.clinicalConclusion,body.targetOutcome,JSON.stringify({text:body.routine}),JSON.stringify({text:body.medication||""}),JSON.stringify({text:body.instructions||""}),status,status==="approved"?now:null,status==="approved"?now:null,now,now).run();
   if(status==="approved"){
    const journey=await db.prepare("SELECT * FROM journey_instances WHERE id=? AND tenant_id=?").bind(journeyId,tenantId).first<Record<string,unknown>>();if(!journey)throw new Error("JOURNEY_NOT_FOUND");const approve=transitionJourney({currentState:String(journey.current_state),event:"doctor_plan_approved",actorRoles:ctx.roles,completedSessions:Number(journey.completed_sessions),sessionTarget:Number(journey.session_target)});const close=transitionJourney({currentState:approve.toState,event:"consultation_closed",reason:"plan_approved",actorRoles:ctx.roles,completedSessions:Number(journey.completed_sessions),sessionTarget:Number(journey.session_target)});
    await db.batch([db.prepare("UPDATE journey_instances SET current_state=?,version=version+2,updated_at=? WHERE id=? AND version=?").bind(close.toState,now,journeyId,journey.version),...[[approve.event,approve.fromState,approve.toState],[close.event,close.fromState,close.toState]].map(e=>db.prepare("INSERT INTO journey_events (id,tenant_id,journey_id,event_type,from_state,to_state,actor_id,actor_role,reason,occurred_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,journeyId,e[0],e[1],e[2],user.id,ctx.roles[0],e[0]==="consultation_closed"?"plan_approved":null,now,now,now))]);
    const taskCount=await db.prepare("SELECT COUNT(*) count FROM routine_tasks WHERE patient_id=? AND scheduled_for=?").bind(patientId,now.slice(0,10)).first<{count:number}>();
    if(!taskCount?.count)await db.batch([
     db.prepare("INSERT INTO routine_tasks (id,tenant_id,patient_id,title_ar,title_en,period,instructions_ar,instructions_en,scheduled_for,status,created_at,updated_at) VALUES (?,?,?,'روتين الصباح المعتمد','Approved morning routine','morning',?,?,?,'pending',?,?)").bind(crypto.randomUUID(),tenantId,patientId,String(body.routine),String(body.routine),now.slice(0,10),now,now),
     db.prepare("INSERT INTO routine_tasks (id,tenant_id,patient_id,title_ar,title_en,period,instructions_ar,instructions_en,scheduled_for,status,created_at,updated_at) VALUES (?,?,?,'روتين المساء المعتمد','Approved evening routine','evening',?,?,?,'pending',?,?)").bind(crypto.randomUUID(),tenantId,patientId,String(body.medication||body.routine),String(body.medication||body.routine),now.slice(0,10),now,now)
    ]);
    await db.prepare("INSERT OR IGNORE INTO commercial_events (id,tenant_id,clinic_id,patient_id,event_type,source,currency,dedupe_key,occurred_at,recorded_by,created_at,updated_at) VALUES (?,?,?,?, 'program_started','clinical_assessment','JOD',?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,clinicId,patientId,`program_started:${journeyId}`,now,user.id,now,now).run();
   }
  } else if(body.action==="session_complete"){
   validateSession({deviceType:body.deviceType,rationale:body.rationale,sessionNumber:Number(body.sessionNumber)});const journey=await db.prepare("SELECT * FROM journey_instances WHERE id=? AND tenant_id=?").bind(journeyId,tenantId).first<Record<string,unknown>>();if(!journey)throw new Error("JOURNEY_NOT_FOUND");const moved=transitionJourney({currentState:String(journey.current_state),event:"session_completed",actorRoles:ctx.roles,completedSessions:Number(journey.completed_sessions),sessionTarget:Number(journey.session_target)});
   await db.batch([db.prepare("INSERT INTO treatment_sessions (id,tenant_id,clinic_id,patient_id,journey_id,session_number,device_type,rationale,parameters_json,response_notes,physician_id,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,clinicId,patientId,journeyId,body.sessionNumber,body.deviceType,body.rationale,JSON.stringify({text:body.parameters||""}),body.responseNotes||null,user.id,now,now,now),db.prepare("UPDATE journey_instances SET completed_sessions=?,version=version+1,updated_at=? WHERE id=? AND version=?").bind(moved.completedSessions,now,journeyId,journey.version),db.prepare("INSERT INTO journey_events (id,tenant_id,journey_id,event_type,from_state,to_state,actor_id,actor_role,occurred_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,journeyId,moved.event,moved.fromState,moved.toState,user.id,ctx.roles[0],now,now,now)]);
  } else if(body.action==="daily_decision"){
   validateDailyDecision(body);await db.prepare("INSERT INTO clinical_decisions (id,tenant_id,clinic_id,patient_id,journey_id,decision_type,decision,rationale,physician_id,effective_at,created_at,updated_at) VALUES (?,?,?,?,?,'daily_review',?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,clinicId,patientId,journeyId,body.decision,body.rationale,user.id,now,now,now).run();
  } else if(body.action==="note_add"){
   if(!String(body.note||"").trim())throw new Error("NOTE_REQUIRED");await db.prepare("INSERT INTO doctor_notes (id,tenant_id,patient_id,journey_id,physician_id,note_type,body,visibility,created_at,updated_at) VALUES (?,?,?,?,?,'clinical',?,'clinical_team',?,?)").bind(crypto.randomUUID(),tenantId,patientId,journeyId,user.id,body.note,now,now).run();
  } else if(body.action==="alert_update"){
   const status=body.status==="resolved"?"resolved":"acknowledged";await db.prepare("UPDATE alerts SET status=?,owner_id=?,resolved_at=?,resolution=?,updated_at=? WHERE id=? AND tenant_id=?").bind(status,user.id,status==="resolved"?now:null,status==="resolved"?String(body.resolution||""):null,now,body.alertId,tenantId).run();
  } else if(body.action==="outcome_finalize"){
   const conclusion=String(body.physicianConclusion||"").trim();if(!conclusion)throw new Error("PHYSICIAN_CONCLUSION_REQUIRED");const metrics=await db.prepare("SELECT am.metric,am.value,am.measured_at FROM assessment_metrics am JOIN assessments a ON a.id=am.assessment_id WHERE a.patient_id=? AND am.tenant_id=? AND am.review_state='approved' ORDER BY am.measured_at").bind(patientId,tenantId).all<Record<string,unknown>>();if(!metrics.results.length)throw new Error("APPROVED_METRICS_REQUIRED");const grouped=new Map<string,Record<string,unknown>[]>();for(const m of metrics.results){const key=String(m.metric);grouped.set(key,[...(grouped.get(key)||[]),m])}const baseline=Object.fromEntries([...grouped].map(([k,v])=>[k,v[0]])),final=Object.fromEntries([...grouped].map(([k,v])=>[k,v.at(-1)]));const existing=await db.prepare("SELECT id FROM outcome_documents WHERE patient_id=? AND tenant_id=? ORDER BY created_at DESC LIMIT 1").bind(patientId,tenantId).first<{id:string}>();const id=existing?.id||crypto.randomUUID();if(existing)await db.prepare("UPDATE outcome_documents SET baseline_json=?,final_json=?,physician_conclusion=?,completed_at=?,updated_at=? WHERE id=?").bind(JSON.stringify(baseline),JSON.stringify(final),conclusion,now,now,id).run();else await db.prepare("INSERT INTO outcome_documents (id,tenant_id,patient_id,program_id,baseline_json,final_json,physician_conclusion,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,tenantId,patientId,journeyId,JSON.stringify(baseline),JSON.stringify(final),conclusion,now,now,now).run();
  } else if(body.action==="template_approve"){
   if(!medicalDirectorRole(ctx.roles))return NextResponse.json({error:"MEDICAL_DIRECTOR_REQUIRED"},{status:403});const configId=String(body.configId??"");await db.batch([db.prepare("UPDATE clinical_configurations SET status='published',reviewer_id=?,effective_at=?,updated_at=? WHERE id=? AND tenant_id=? AND status='draft'").bind(user.id,now,now,configId,tenantId),db.prepare("INSERT INTO approvals (id,tenant_id,entity_type,entity_id,status,requested_by,decided_by,decision_reason,decided_at,created_at,updated_at) VALUES (?,?,'clinical_configuration',?,'approved',?,?,?, ?,?,?)").bind(crypto.randomUUID(),tenantId,configId,String(body.requestedBy||user.id),user.id,String(body.reason||"Medical Director approval"),now,now,now)]);
  } else return NextResponse.json({error:"UNKNOWN_ACTION"},{status:400});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"ACTION_REJECTED"},{status:409});}
 await db.prepare("INSERT INTO audit_logs (id,tenant_id,actor_id,entity_type,entity_id,action,after_json,occurred_at,created_at,updated_at) VALUES (?,?,?,'clinical',?,?,?, ?,?,?)").bind(crypto.randomUUID(),tenantId,user.id,patientId||String(body.configId||""),body.action,JSON.stringify(body),now,now,now).run();
 return NextResponse.json({ok:true});
}
