"use client";
import type {ReactNode} from "react";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Activity,CalendarDays,Camera,Check,ChevronRight,ClipboardCheck,Clock3,FileText,RefreshCw,Search,ShieldCheck,UserPlus,UsersRound} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Progress} from "@/components/ui/progress";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Textarea} from "@/components/ui/textarea";
import {toast,Toaster} from "sonner";
import CommunicationsCenter from "./communications-center";
import ReportsCenter from "./reports-center";
import IntegrationsCenter from "./integrations-center";

type RecordRow=Record<string,string|number|null>;
type Data={patients:RecordRow[];intakes:RecordRow[];imaging:RecordRow[];appointments:RecordRow[];reschedules:RecordRow[];roles:string[]};
const empty:Data={patients:[],intakes:[],imaging:[],appointments:[],reschedules:[],roles:[]};
const nameOf=(x:RecordRow)=>String(x.full_name_ar||x.full_name_en||x.reference_code||"—");

export default function AdminOperationsPortal({arabic}:{arabic:boolean}){
 const t=(ar:string,en:string)=>arabic?ar:en;
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[query,setQuery]=useState(""),[open,setOpen]=useState(false);
 const [form,setForm]=useState({fullName:"",mobile:"",concern:"",goal:""});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin/operations",{cache:"no-store"});const body=await r.json();if(body.error==="SETUP_REQUIRED")setSetup(true);else if(!r.ok)throw new Error(body.error);else{setData(body);setSetup(false)}}catch{toast.error(arabic?"تعذر تحميل بيانات التشغيل":"Could not load operations data")}finally{setLoading(false)}},[arabic]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const action=async(payload:Record<string,unknown>,success:string)=>{const r=await fetch("/api/admin/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok){toast.error(String(body.error||t("تعذر تنفيذ الإجراء","Action failed")));return false}toast.success(success);await load();return true};
 const initialize=async()=>{const r=await fetch("/api/setup",{method:"POST"});if(r.ok){toast.success(t("تم إنشاء مساحة العمل الآمنة","Secure workspace initialized"));await load()}else toast.error(t("تعذر إتمام الإعداد","Setup could not be completed"))};
 const register=async()=>{if(await action({action:"register_patient",...form},t("تم إنشاء سجل المريض","Patient record created"))){setOpen(false);setForm({fullName:"",mobile:"",concern:"",goal:""})}};
 const filtered=useMemo(()=>data.patients.filter(p=>nameOf(p).toLowerCase().includes(query.toLowerCase())||String(p.reference_code).toLowerCase().includes(query.toLowerCase())),[data.patients,query]);
 if(setup)return <main dir={arabic?"rtl":"ltr"} className="mx-auto max-w-3xl px-5 py-16"><div className="rounded-[2rem] border bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto size-12 text-purple-700"/><h1 className="mt-5 text-2xl font-semibold text-purple-950">{t("تهيئة مساحة تشغيل Derma Glow","Initialize Derma Glow operations")}</h1><p className="mx-auto mt-3 max-w-xl text-slate-500">{t("قاعدة البيانات فارغة. يمكن لأول مالك مصادق عليه فقط إنشاء المؤسسة والفرع ومنح نفسه صلاحية المدير الأعلى.","The database is empty. Only the first authenticated owner can create the organization and clinic and receive the Super Admin role.")}</p><Button className="mt-6 bg-purple-950" onClick={initialize}>{t("تهيئة مساحة العمل","Initialize workspace")}</Button></div><Toaster richColors/></main>;
 return <main dir={arabic?"rtl":"ltr"} className="mx-auto max-w-[1650px] px-4 py-6 lg:px-7"><Toaster richColors/><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-semibold text-purple-700">{t("مركز تشغيل البرنامج","PROGRAM OPERATIONS CENTER")}</div><h1 className="mt-2 text-3xl font-semibold text-purple-950">{t("الإدارة والاستقبال","Admin & Reception")}</h1><p className="mt-2 text-slate-500">{t("سجل موحّد من وصول المريض حتى تسليم الملف للطبيب.","One patient record from arrival through physician handoff.")}</p></div><div className="flex gap-2"><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className={loading?"animate-spin":""}/>{t("تحديث","Refresh")}</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-purple-950"><UserPlus/>{t("مريض جديد","New patient")}</Button></DialogTrigger><DialogContent dir={arabic?"rtl":"ltr"}><DialogHeader><DialogTitle>{t("إنشاء سجل مريض موحّد","Create unified patient record")}</DialogTitle><DialogDescription>{t("سيُنشئ النظام سجل المريض ورحلة استقبال مرتبطة به دون تكرار.","This creates one patient record and a linked reception journey.")}</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><div><Label>{t("الاسم الكامل","Full name")}</Label><Input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} className="mt-2"/></div><div><Label>{t("رقم الهاتف","Mobile")}</Label><Input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} className="mt-2" dir="ltr"/></div><div><Label>{t("المشكلة الأساسية بصياغة المريض","Primary concern in patient’s words")}</Label><Textarea value={form.concern} onChange={e=>setForm({...form,concern:e.target.value})} className="mt-2"/></div><div><Label>{t("الهدف الشخصي","Personal goal")}</Label><Textarea value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})} className="mt-2"/></div><Button onClick={register} disabled={!form.fullName.trim()||!form.mobile.trim()} className="bg-purple-950">{t("إنشاء السجل","Create record")}</Button></div></DialogContent></Dialog></div></div>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[[data.intakes.length,t("في الاستقبال","Reception queue"),UsersRound],[data.imaging.length,t("بانتظار التصوير","Imaging queue"),Camera],[data.reschedules.length,t("طلبات تغيير","Reschedule requests"),CalendarDays],[data.appointments.length,t("مواعيد قادمة","Upcoming appointments"),Clock3],[data.patients.length,t("مرضى نشطون","Active patients"),Activity]].map(([n,l,I])=><div key={String(l)} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between"><div><div className="text-2xl font-semibold text-purple-950">{String(n)}</div><div className="mt-1 text-sm text-slate-500">{String(l)}</div></div>{typeof I!=="string"&&<I className="size-5 text-purple-600"/>}</div></div>)}</div>
 <Tabs defaultValue="dashboard"><TabsList className="h-auto max-w-full flex-wrap justify-start bg-white p-1.5 shadow-sm"><TabsTrigger value="dashboard">{t("اليوم","Today")}</TabsTrigger><TabsTrigger value="registry">{t("سجل المرضى","Patient Registry")}</TabsTrigger><TabsTrigger value="reception">{t("الاستقبال","Reception Queue")}</TabsTrigger><TabsTrigger value="imaging">{t("التصوير","Imaging Queue")}</TabsTrigger><TabsTrigger value="scheduling">{t("الجدولة","Scheduling")}</TabsTrigger><TabsTrigger value="coordination">{t("تنسيق الرحلة","Journey Coordination")}</TabsTrigger><TabsTrigger value="communications">{t("التواصل والأتمتة","Communications")}</TabsTrigger><TabsTrigger value="reports">{t("التقارير والإثبات","Reports & Evidence")}</TabsTrigger><TabsTrigger value="integrations">{t("الربط والإطلاق","Integrations")}</TabsTrigger></TabsList>
 <TabsContent value="dashboard" className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Queue title={t("العمل المطلوب الآن","Required now")} emptyText={t("لا توجد إجراءات معلقة","No pending actions")}>{data.intakes.slice(0,5).map(x=><QueueRow key={String(x.id)} name={nameOf(x)} meta={`${x.reference_code} · ${String(x.status).replaceAll("_"," ")}`} badge={`${x.profile_completeness}%`} />)}</Queue><Queue title={t("حالة التسليم للطبيب","Physician handoff readiness")} emptyText={t("لا توجد ملفات جاهزة","No ready files")}>{data.intakes.filter(x=>x.status==="ready_for_doctor").map(x=><QueueRow key={String(x.id)} name={nameOf(x)} meta={String(x.personal_goal||t("الهدف غير مسجل","Goal not recorded"))} badge={t("جاهز","Ready")}/>)}</Queue></TabsContent>
 <TabsContent value="registry" className="mt-5"><section className="overflow-hidden rounded-3xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-semibold text-purple-950">{t("السجل الموحّد","Unified registry")}</h2><p className="text-sm text-slate-500">{t("لا يتم إنشاء ملف جديد لكل مرحلة.","One record persists across every stage.")}</p></div><div className="relative"><Search className={`absolute top-2.5 size-4 text-slate-400 ${arabic?"right-3":"left-3"}`}/><Input value={query} onChange={e=>setQuery(e.target.value)} className={arabic?"pr-9":"pl-9"} placeholder={t("بحث…","Search…")}/></div></div><div className="divide-y">{filtered.map(x=><div key={String(x.id)} className="grid gap-3 p-4 md:grid-cols-[1.2fr_.8fr_.7fr_1fr]"><div><div className="font-medium text-purple-950">{nameOf(x)}</div><div className="text-sm text-slate-400">{x.reference_code} · {x.mobile}</div></div><div><div className="text-xs text-slate-400">{t("المرحلة","Stage")}</div><div className="mt-1 text-sm">{String(x.current_state||"REGISTERED").replaceAll("_"," ")}</div></div><div><div className="text-xs text-slate-400">{t("اكتمال الملف","Completeness")}</div><Progress value={Number(x.profile_completeness||0)} className="mt-2 h-2"/></div><div className="text-end"><Badge variant="outline">{String(x.status)}</Badge></div></div>)}</div></section></TabsContent>
 <TabsContent value="reception" className="mt-5"><Queue title={t("مسار الاستقبال خطوة بخطوة","Reception workflow")} emptyText={t("لا يوجد مرضى في قائمة الاستقبال","Reception queue is clear")}>{data.intakes.map(x=><div key={String(x.id)} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-semibold text-purple-950">{nameOf(x)}</div><div className="mt-1 text-sm text-slate-500">{x.reference_code} · {String(x.status).replaceAll("_"," ")}</div></div><div className="flex flex-wrap gap-2">{x.status==="awaiting_arrival"&&<Button size="sm" onClick={()=>action({action:"check_in",intakeId:x.id},t("تم تسجيل الوصول","Patient checked in"))}>{t("تسجيل الوصول","Check in")}</Button>}{x.status==="checked_in"&&x.medical_consent_status!=="signed"&&<Button size="sm" onClick={()=>action({action:"record_consent",intakeId:x.id},t("تم توثيق الموافقة الطبية","Medical consent recorded"))}><FileText/>{t("توثيق الموافقة","Record consent")}</Button>}{x.medical_consent_status==="signed"&&x.status!=="imaging"&&x.status!=="ready_for_doctor"&&<Button size="sm" onClick={()=>action({action:"send_to_imaging",intakeId:x.id},t("تم الإرسال للتصوير","Sent to imaging"))}><Camera/>{t("إرسال للتصوير","Send to imaging")}</Button>}{x.status==="ready_for_doctor"&&<Button size="sm" className="bg-purple-950" onClick={()=>action({action:"notify_doctor",intakeId:x.id},t("تم إخطار الطبيب","Physician notified"))}>{t("إخطار الطبيب","Notify doctor")}</Button>}</div></div><div className="mt-4 grid grid-cols-4 gap-2">{[[t("الوصول","Arrival"),!!x.checked_in_at],[t("الموافقة","Consent"),x.medical_consent_status==="signed"],[t("التصوير","Imaging"),["imaging","ready_for_doctor"].includes(String(x.status))],[t("الطبيب","Doctor"),x.status==="ready_for_doctor"]].map(([l,done])=><div key={String(l)} className={`rounded-xl p-2 text-center text-xs ${done?"bg-emerald-50 text-emerald-700":"bg-slate-50 text-slate-400"}`}>{done&&<Check className="mx-auto mb-1 size-3"/>}{String(l)}</div>)}</div></div>)}</Queue></TabsContent>
 <TabsContent value="imaging" className="mt-5"><Queue title={t("قائمة التصوير المعياري","Standardized imaging queue")} emptyText={t("لا توجد حالات بانتظار التصوير","No patients awaiting imaging")}>{data.intakes.filter(x=>x.status==="imaging").map(x=><div key={String(x.id)} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border p-4"><div><div className="font-semibold">{nameOf(x)}</div><div className="text-sm text-slate-400">{x.reference_code} · Observe baseline</div></div><div className="flex flex-wrap items-center gap-3 text-sm text-slate-500"><span><Check className="inline size-4 text-emerald-600"/> {t("زاوية","Angle")}</span><span><Check className="inline size-4 text-emerald-600"/> {t("إضاءة","Light")}</span><span><Check className="inline size-4 text-emerald-600"/> {t("مسافة","Distance")}</span><Button onClick={()=>action({action:"complete_imaging",intakeId:x.id,resultReference:`OBS-${x.reference_code}`},t("اكتمل التصوير وأصبح الملف جاهزًا","Imaging completed; file is ready"))}>{t("إكمال وربط النتيجة","Complete & link")}</Button></div></div>)}</Queue></TabsContent>
 <TabsContent value="scheduling" className="mt-5 grid gap-4 lg:grid-cols-2"><Queue title={t("المواعيد القادمة","Upcoming appointments")} emptyText={t("لا توجد مواعيد","No appointments")}>{data.appointments.map(x=><QueueRow key={String(x.id)} name={nameOf(x)} meta={`${x.service_name} · ${new Date(String(x.starts_at)).toLocaleString(arabic?"ar-JO":"en-GB")}`} badge={String(x.status)}/>)}</Queue><Queue title={t("طلبات تغيير الموعد","Reschedule requests")} emptyText={t("لا توجد طلبات معلقة","No pending requests")}>{data.reschedules.map(x=><div key={String(x.id)} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><div className="font-medium">{nameOf(x)}</div><div className="text-sm text-slate-500">{new Date(String(x.preferred_starts_at)).toLocaleString(arabic?"ar-JO":"en-GB")}</div><div className="text-xs text-slate-400">{x.reason}</div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>action({action:"resolve_reschedule",requestId:x.id,decision:"declined"},t("تم رفض الطلب","Request declined"))}>{t("رفض","Decline")}</Button><Button size="sm" onClick={()=>action({action:"resolve_reschedule",requestId:x.id,decision:"approved"},t("تم اعتماد الموعد الجديد","New time approved"))}>{t("اعتماد","Approve")}</Button></div></div>)}</Queue></TabsContent>
 <TabsContent value="coordination" className="mt-5"><Queue title={t("متابعة اكتمال الرحلة","Journey coordination") } emptyText={t("لا توجد سجلات","No records")}>{data.patients.map(x=><div key={String(x.id)} className="flex items-center justify-between rounded-2xl border p-4"><div><div className="font-medium">{nameOf(x)}</div><div className="text-sm text-slate-400">{String(x.current_state||"REGISTERED").replaceAll("_"," ")} · {Number(x.completed_sessions||0)} / {Number(x.session_target||9)} {t("جلسات","sessions")}</div></div><div className="flex items-center gap-3"><Progress value={(Number(x.completed_sessions||0)/Number(x.session_target||9))*100} className="hidden w-28 sm:block"/><Button variant="ghost" size="icon"><ChevronRight/></Button></div></div>)}</Queue></TabsContent>
 <TabsContent value="communications" className="mt-5"><CommunicationsCenter arabic={arabic}/></TabsContent><TabsContent value="reports" className="mt-5"><ReportsCenter arabic={arabic}/></TabsContent><TabsContent value="integrations" className="mt-5"><IntegrationsCenter arabic={arabic}/></TabsContent></Tabs></main>;
}

function Queue({title,emptyText,children}:{title:string;emptyText:string;children:ReactNode}){const has=Array.isArray(children)?children.length>0:!!children;return <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold text-purple-950">{title}</h2>{has?<div className="space-y-3">{children}</div>:<div className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-400"><ClipboardCheck className="mx-auto mb-2 size-6"/>{emptyText}</div>}</section>}
function QueueRow({name,meta,badge}:{name:string;meta:string;badge:string}){return <div className="flex items-center justify-between gap-3 rounded-2xl border p-4"><div><div className="font-medium text-purple-950">{name}</div><div className="mt-1 text-sm text-slate-400">{meta}</div></div><Badge variant="outline">{badge}</Badge></div>}
