"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {BellRing,Bot,Check,Clock3,MessageCircle,Play,RefreshCw,Send,ShieldAlert} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Input} from "@/components/ui/input";
import {Switch} from "@/components/ui/switch";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {toast} from "sonner";
type Row=Record<string,any>;type Data={threads:Row[];messages:Row[];outbox:Row[];templates:Row[];rules:Row[];tasks:Row[]};const empty:Data={threads:[],messages:[],outbox:[],templates:[],rules:[],tasks:[]};
const name=(r:Row,ar:boolean)=>String((ar?r.full_name_ar:r.full_name_en)||r.full_name_ar||r.full_name_en||r.reference_code||"—");
export default function CommunicationsCenter({arabic}:{arabic:boolean}){const t=(ar:string,en:string)=>arabic?ar:en;const [data,setData]=useState(empty),[selected,setSelected]=useState(""),[reply,setReply]=useState(""),[loading,setLoading]=useState(true);
 const autoRan=useRef(false);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch("/api/communications/workspace",{cache:"no-store"});const b=await r.json();if(r.ok){setData(b);setSelected(s=>s||String(b.threads?.[0]?.id||""))}else toast.error(b.error||t("تعذر تحميل مركز التواصل","Could not load communication center"));setLoading(false)},[arabic]);useEffect(()=>{void load()},[load]);
 const act=async(payload:Row,message:string,silent=false)=>{const r=await fetch("/api/communications/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){toast.error(b.error||t("تعذر التنفيذ","Action failed"));return}if(!silent)toast.success(payload.action==="run_automations"?`${message}: ${b.queued||0}`:message);setReply("");await load()};useEffect(()=>{if(!loading&&!autoRan.current){autoRan.current=true;void act({action:"run_automations"},"",true)}},[loading]);const thread=data.threads.find(x=>x.id===selected);const messages=useMemo(()=>data.messages.filter(x=>x.thread_id===selected),[data.messages,selected]);
 return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-3xl bg-purple-950 p-5 text-white"><div><div className="flex items-center gap-2 text-sm text-purple-200"><Bot className="size-4"/>{t("تنظيم آلي تحت الإشراف","SUPERVISED AUTOMATION")}</div><h2 className="mt-1 text-xl font-semibold">{t("الرسائل والتذكيرات والمتابعة","Messaging, reminders & follow-up")}</h2><p className="mt-1 text-sm text-purple-200">{t("الأتمتة تنظّم وتنبّه فقط؛ لا تشخّص ولا تغيّر العلاج.","Automation organizes and flags only; it never diagnoses or changes treatment.")}</p></div><div className="flex gap-2"><Button variant="outline" className="border-white/20 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={load}><RefreshCw className={loading?"animate-spin":""}/>{t("تحديث","Refresh")}</Button><Button className="bg-amber-400 text-purple-950 hover:bg-amber-300" onClick={()=>act({action:"run_automations"},t("تم إنشاء الإشعارات المستحقة","Due notifications queued"))}><Play/>{t("تشغيل المستحق الآن","Run due now")}</Button></div></div>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[data.threads.reduce((n,x)=>n+Number(x.unread_count||0),0),t("رسائل غير مقروءة","Unread messages"),MessageCircle],[data.outbox.filter(x=>x.status==="queued").length,t("في صندوق الإرسال","Queued notifications"),BellRing],[data.tasks.length,t("مهام متابعة","Follow-up tasks"),ShieldAlert],[data.rules.filter(x=>x.enabled).length,t("قواعد فعّالة","Active rules"),Bot]].map(([n,l,I]:any)=><div key={l} className="rounded-2xl border bg-white p-4"><I className="size-5 text-purple-600"/><div className="mt-3 text-2xl font-semibold text-purple-950">{n}</div><div className="text-sm text-slate-500">{l}</div></div>)}</div>
 <Tabs defaultValue="inbox"><TabsList className="h-auto flex-wrap bg-white p-1.5"><TabsTrigger value="inbox">{t("صندوق المحادثات","Inbox")}</TabsTrigger><TabsTrigger value="outbox">{t("صندوق الإرسال","Outbox")}</TabsTrigger><TabsTrigger value="automation">{t("قواعد الأتمتة","Automation rules")}</TabsTrigger><TabsTrigger value="tasks">{t("مهام المنسق","Coordinator tasks")}</TabsTrigger><TabsTrigger value="templates">{t("القوالب","Templates")}</TabsTrigger></TabsList>
  <TabsContent value="inbox" className="mt-4 grid min-h-[520px] gap-4 lg:grid-cols-[320px_1fr]"><aside className="overflow-hidden rounded-3xl border bg-white"><div className="border-b p-4 font-semibold">{t("المحادثات الآمنة","Secure conversations")}</div>{data.threads.map(x=><button key={x.id} onClick={()=>setSelected(String(x.id))} className={`w-full border-b p-4 text-start ${selected===x.id?"bg-purple-50":""}`}><div className="flex justify-between gap-2"><span className="font-medium">{name(x,arabic)}</span>{Number(x.unread_count)>0&&<Badge>{x.unread_count}</Badge>}</div><div className="mt-1 text-sm text-slate-500">{x.category} · {x.reference_code}</div></button>)}{!data.threads.length&&<div className="p-8 text-center text-sm text-slate-400">{t("لا توجد محادثات بعد","No conversations yet")}</div>}</aside><section className="flex min-h-[520px] flex-col rounded-3xl border bg-white p-5">{thread?<><div className="border-b pb-4"><div className="font-semibold text-purple-950">{name(thread,arabic)}</div><div className="text-sm text-slate-500">{thread.reference_code} · {thread.category}</div></div><div className="flex-1 space-y-3 overflow-y-auto py-5">{messages.map(m=><div key={m.id} className={`max-w-[80%] rounded-2xl p-3 text-sm ${m.sender_role==="patient"?"bg-slate-100":"ms-auto bg-purple-950 text-white"}`}><div>{m.body}</div><div className={`mt-2 text-xs ${m.sender_role==="patient"?"text-slate-400":"text-purple-200"}`}>{new Date(m.sent_at).toLocaleString(arabic?"ar-JO":"en-GB")} · {m.delivery_status}</div></div>)}</div><div className="flex gap-2 border-t pt-4"><Input value={reply} onChange={e=>setReply(e.target.value)} placeholder={t("اكتب ردًا شخصيًا…","Write a personal reply…")} onKeyDown={e=>{if(e.key==="Enter"&&reply.trim())void act({action:"staff_send",threadId:selected,message:reply},t("تم إرسال الرد","Reply sent"))}}/><Button disabled={!reply.trim()} onClick={()=>act({action:"staff_send",threadId:selected,message:reply},t("تم إرسال الرد","Reply sent"))}><Send/></Button></div></>:<div className="m-auto text-sm text-slate-400">{t("اختر محادثة","Select a conversation")}</div>}</section></TabsContent>
  <TabsContent value="outbox" className="mt-4"><div className="space-y-3">{data.outbox.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><div className="font-medium">{name(x,arabic)}</div><div className="mt-1 text-sm text-slate-500">{x.body}</div><div className="mt-1 text-xs text-slate-400">{x.rule_key} · {new Date(x.scheduled_for).toLocaleString(arabic?"ar-JO":"en-GB")}</div></div><Badge variant="outline">{x.status}</Badge></div>)}</div></TabsContent>
  <TabsContent value="automation" className="mt-4 grid gap-3 md:grid-cols-2">{data.rules.map(x=><label key={x.id} className="flex items-start justify-between gap-4 rounded-3xl border bg-white p-5"><span><span className="block font-semibold text-purple-950">{arabic?x.name_ar:x.name_en}</span><span className="mt-1 block text-sm text-slate-500">{x.trigger_type} · {x.channel}</span>{Boolean(x.requires_clinical_approval)&&<Badge className="mt-3 bg-amber-50 text-amber-800">{t("يتطلب إشرافًا سريريًا","Clinical oversight required")}</Badge>}</span><Switch checked={Boolean(x.enabled)} onCheckedChange={v=>void act({action:"rule_toggle",ruleId:x.id,enabled:v},t("تم تحديث القاعدة","Rule updated"))}/></label>)}</TabsContent>
  <TabsContent value="tasks" className="mt-4 space-y-3">{data.tasks.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><div className="font-medium">{name(x,arabic)}</div><div className="text-sm text-slate-500">{x.title} · {x.reference_code}</div><div className="mt-1 text-xs text-slate-400"><Clock3 className="me-1 inline size-3"/>{new Date(x.due_at).toLocaleString(arabic?"ar-JO":"en-GB")}</div></div><Button size="sm" onClick={()=>act({action:"task_resolve",taskId:x.id},t("تم إغلاق مهمة المتابعة","Follow-up task resolved"))}><Check/>{t("تمت المتابعة","Resolved")}</Button></div>)}</TabsContent>
  <TabsContent value="templates" className="mt-4 grid gap-3 md:grid-cols-2">{data.templates.map(x=><div key={x.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between gap-3"><div className="font-semibold text-purple-950">{arabic?x.name_ar:x.name_en}</div><Badge variant="outline">v{x.version} · {x.status}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-600">{arabic?x.body_ar:x.body_en}</p></div>)}</TabsContent>
 </Tabs></section>}
