"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,Camera,Check,ClipboardCheck,Eye,FileCheck2,Images,RefreshCw,Search,ShieldCheck,Stethoscope} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Progress} from "@/components/ui/progress";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Textarea} from "@/components/ui/textarea";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {toast,Toaster} from "sonner";

type Row=Record<string,string|number|null>;
type Detail={patient:Row;consultations:Row[];sessions:Row[];decisions:Row[];notes:Row[];metrics:Row[];appointments:Row[];events:Row[]};
type Data={patients:Row[];detail:Detail|null;alerts:Row[];templates:Row[];roles?:string[]};
const blank:Data={patients:[],detail:null,alerts:[],templates:[]};
const nameOf=(x:Row)=>String(x.full_name_ar||x.full_name_en||x.reference_code||"—");

export default function DoctorPortal({arabic}:{arabic:boolean}){
 const t=(ar:string,en:string)=>arabic?ar:en;
 const [data,setData]=useState<Data>(blank),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[mode,setMode]=useState("side");
 const [consultation,setConsultation]=useState({severity:"mid_to_moderate",clinicalConclusion:"",targetOutcome:"",routine:"",medication:"",instructions:""});
 const [session,setSession]=useState({deviceType:"Accure",rationale:"",parameters:"",responseNotes:""}),[decision,setDecision]=useState({decision:"no_change",rationale:""}),[note,setNote]=useState(""),[outcomeConclusion,setOutcomeConclusion]=useState("");
 const load=useCallback(async(patientId?:string)=>{setLoading(true);try{const suffix=patientId?`?patientId=${encodeURIComponent(patientId)}`:"";const r=await fetch(`/api/doctor/workspace${suffix}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body);if(body.patients?.[0])setSelected(current=>current||String(body.patients[0].id));const latest=body.detail?.consultations?.[0];if(latest)setConsultation({severity:String(latest.severity||"mid_to_moderate"),clinicalConclusion:String(latest.clinical_conclusion||""),targetOutcome:String(latest.target_outcome||""),routine:jsonText(latest.routine_json),medication:jsonText(latest.medication_json),instructions:jsonText(latest.instructions_json)})}catch(e){toast.error(e instanceof Error?e.message:(arabic?"تعذر تحميل مساحة الطبيب":"Could not load physician workspace"))}finally{setLoading(false)}},[arabic]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const choose=(id:string)=>{setSelected(id);void load(id)};
 const act=async(payload:Record<string,unknown>,message:string)=>{const r=await fetch("/api/doctor/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok){toast.error(String(body.error||"Action failed"));return}toast.success(message);await load(selected)};
 const patient=data.detail?.patient;const journeyId=String(patient?.journey_id||"");
 const filtered=useMemo(()=>data.patients.filter(p=>nameOf(p).toLowerCase().includes(query.toLowerCase())||String(p.reference_code).toLowerCase().includes(query.toLowerCase())),[data.patients,query]);
 const high=data.patients.filter(p=>Number(p.risk_rank)===3).length;
 return <main dir={arabic?"rtl":"ltr"} className="mx-auto max-w-[1800px] px-4 py-5 lg:px-6"><Toaster richColors/><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-semibold text-purple-700"><Stethoscope className="size-4"/>{t("مساحة الطبيب","PHYSICIAN WORKSPACE")}</div><h1 className="mt-2 text-3xl font-semibold text-purple-950">{t("المراجعة والقرار السريري","Clinical review and decisions")}</h1><p className="mt-1 text-slate-500">AI measures. The physician decides.</p></div><div className="flex gap-2"><Badge variant="outline" className="px-3 py-2"><AlertTriangle className="size-4 text-rose-500"/>{high} {t("عالية الأولوية","high priority")}</Badge><Button variant="outline" onClick={()=>load(selected)} disabled={loading}><RefreshCw className={loading?"animate-spin":""}/>{t("تحديث","Refresh")}</Button></div></div>
 <div className="grid min-h-[760px] gap-4 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-4"><h2 className="font-semibold text-purple-950">{t("كل المرضى النشطين","All active patients")}</h2><p className="mt-1 text-sm text-slate-500">{t("مرتبة حسب الخطورة ثم آخر تحديث","Risk first, then latest activity")}</p><div className="relative mt-3"><Search className={`absolute top-2.5 size-4 text-slate-400 ${arabic?"right-3":"left-3"}`}/><Input value={query} onChange={e=>setQuery(e.target.value)} className={arabic?"pr-9":"pl-9"} placeholder={t("بحث…","Search…")}/></div></div><div className="divide-y">{filtered.map(p=><button key={String(p.id)} onClick={()=>choose(String(p.id))} className={`w-full p-4 text-start ${selected===p.id?"bg-purple-50":"hover:bg-slate-50"}`}><div className="flex gap-3"><span className={`mt-1 size-2.5 shrink-0 rounded-full ${Number(p.risk_rank)===3?"bg-rose-500":Number(p.risk_rank)===2?"bg-amber-400":"bg-emerald-500"}`}/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="truncate font-medium text-purple-950">{nameOf(p)}</span>{Number(p.alert_count)>0&&<Badge variant="outline">{p.alert_count}</Badge>}</div><div className="mt-1 text-sm text-slate-500">{p.reference_code}</div><div className="mt-2 text-xs text-slate-400">{String(p.current_state||"REGISTERED").replaceAll("_"," ")} · {p.completed_sessions||0}/{p.session_target||9}</div></div></div></button>)}{!filtered.length&&<div className="p-8 text-center text-sm text-slate-400">{t("لا يوجد مرضى بعد","No patients yet")}</div>}</div></aside>
 <section className="min-w-0">{!patient?<div className="grid h-72 place-items-center rounded-3xl border bg-white text-slate-400"><div className="text-center"><ClipboardCheck className="mx-auto size-9"/><p className="mt-3">{t("اختر مريضًا لبدء المراجعة","Select a patient to begin review")}</p></div></div>:<Tabs defaultValue="overview"><TabsList className="h-auto max-w-full flex-wrap justify-start bg-white p-1.5 shadow-sm"><TabsTrigger value="overview">Patient 360</TabsTrigger><TabsTrigger value="consultation">{t("الاستشارة","Consultation")}</TabsTrigger><TabsTrigger value="session">{t("مراجعة الجلسة","Session Review")}</TabsTrigger><TabsTrigger value="daily">{t("المراجعة اليومية","Daily Review")}</TabsTrigger><TabsTrigger value="alerts">{t("التنبيهات","Alerts")}</TabsTrigger><TabsTrigger value="outcome">{t("توثيق النتيجة","Outcome Evidence")}</TabsTrigger><TabsTrigger value="templates">{t("القوالب السريرية","Clinical Templates")}</TabsTrigger></TabsList>
 <TabsContent value="overview" className="mt-4 space-y-4"><section className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-purple-100 font-semibold text-purple-950">{nameOf(patient).slice(0,1)}</div><div><h2 className="text-xl font-semibold text-purple-950">{nameOf(patient)}</h2><p className="mt-1 text-sm text-slate-500">{patient.reference_code} · {patient.mobile}</p></div></div><div className="flex gap-2"><Badge>{String(patient.current_state).replaceAll("_"," ")}</Badge><Badge variant="outline">{patient.completed_sessions}/{patient.session_target} {t("جلسات","sessions")}</Badge></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Info label={t("المشكلة بصياغة المريض","Patient’s concern")} value={String(patient.primary_concern||"—")}/><Info label={t("الهدف الأصلي","Original goal")} value={String(patient.personal_goal||"—")}/></div></section>
 <section className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="overflow-hidden rounded-3xl bg-[#17131d] p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 font-semibold"><Images className="size-4"/>{t("المقارنة الطولية المعيارية","Standardized longitudinal comparison")}</div><div className="mt-1 text-xs text-white/50">{t("نفس الزاوية والإضاءة والمسافة","Matched angle, light and distance")}</div></div><div className="flex rounded-xl bg-white/10 p-1">{[["side",t("جنبًا إلى جنب","Side")],["flicker",t("وميض","Flicker")],["difference",t("الاختلاف","Difference")]].map(([k,l])=><button key={k} onClick={()=>setMode(k)} className={`rounded-lg px-3 py-1.5 text-xs ${mode===k?"bg-white text-purple-950":"text-white/60"}`}>{l}</button>)}</div></div><div className={`mt-4 grid gap-3 ${mode==="side"?"md:grid-cols-2":""}`}>{(mode==="side"?["Baseline",t("الحالي","Current")]:[mode]).map(label=><div key={label} className={`relative grid h-72 place-items-center overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br ${mode==="difference"?"from-fuchsia-950 via-amber-950 to-purple-950":"from-[#352b3f] via-[#6f5969] to-[#b98f88]"}`}><Eye className="size-9 text-white/60"/><span className="absolute bottom-3 left-3 rounded-lg bg-black/40 px-2 py-1 text-xs">{label}</span></div>)}</div><div className="mt-4 rounded-xl bg-white/8 p-3 text-sm text-white/60"><Check className="me-1 inline size-4 text-emerald-400"/>{t("قياسات وصور مساعدة — التفسير والقرار للطبيب","Supportive measurements and images — interpretation and decision remain with the physician")}</div></div><div className="rounded-3xl border bg-white p-5"><h3 className="font-semibold text-purple-950">{t("جاهزية القرار","Decision readiness")}</h3><div className="mt-4 space-y-4"><Meter label={t("الملف الأساسي","Core record")} value={100}/><Meter label={t("التصوير المعياري","Standardized imaging")} value={100}/><Meter label={t("الخطة المعتمدة","Approved plan")} value={data.detail?.consultations[0]?.status==="approved"?100:0}/></div><div className="mt-5 border-t pt-4"><Label>{t("ملاحظة داخلية","Internal clinical note")}</Label><Textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-2"/><Button className="mt-2 w-full" disabled={!note.trim()} onClick={()=>{void act({action:"note_add",patientId:patient.id,journeyId,note},t("تم حفظ الملاحظة","Note saved"));setNote("")}}>{t("حفظ الملاحظة","Save note")}</Button></div></div></section></TabsContent>
 <TabsContent value="consultation" className="mt-4"><section className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold text-purple-950">{t("الكشف وتحديد البرنامج","Consultation and program definition")}</h2><p className="mt-1 text-sm text-slate-500">{t("قالب منظم مع بقاء القرار بالكامل للطبيب.","Structured documentation with full physician authority.")}</p></div><Badge variant="outline">{data.detail?.consultations[0]?.status||"draft"}</Badge></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div><Label>{t("شدة الحالة","Severity")}</Label><Select value={consultation.severity} onValueChange={v=>setConsultation({...consultation,severity:v})}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="mid_to_moderate">Mid-to-Moderate</SelectItem><SelectItem value="severe">Severe</SelectItem></SelectContent></Select></div><Field label={t("الخلاصة السريرية","Clinical conclusion")} value={consultation.clinicalConclusion} onChange={v=>setConsultation({...consultation,clinicalConclusion:v})}/><Field label={t("النتيجة المستهدفة","Target outcome")} value={consultation.targetOutcome} onChange={v=>setConsultation({...consultation,targetOutcome:v})}/><Field label={t("الروتين الصباحي والمسائي","AM/PM routine")} value={consultation.routine} onChange={v=>setConsultation({...consultation,routine:v})}/><Field label={t("الدواء الموصوف","Medication instructions")} value={consultation.medication} onChange={v=>setConsultation({...consultation,medication:v})}/><Field label={t("تعليمات الطبيب","Physician instructions")} value={consultation.instructions} onChange={v=>setConsultation({...consultation,instructions:v})}/></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>act({action:"consultation_save",patientId:patient.id,journeyId,...consultation},t("تم حفظ المسودة","Draft saved"))}>{t("حفظ مسودة","Save draft")}</Button><Button className="bg-purple-950" onClick={()=>act({action:"consultation_approve_close",patientId:patient.id,journeyId,...consultation},t("تم اعتماد الخطة وإغلاق الكشف","Plan approved and consultation closed"))}><FileCheck2/>{t("اعتماد وإغلاق الكشف","Approve & close")}</Button></div></section></TabsContent>
 <TabsContent value="session" className="mt-4"><section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold text-purple-950">{t("تاريخ الجلسات","Session history")}</h2><div className="mt-4 space-y-3">{data.detail?.sessions.map(s=><div key={String(s.id)} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between"><span className="font-medium">Session {s.session_number}</span><Badge variant="outline">{s.device_type}</Badge></div><p className="mt-2 text-sm text-slate-500">{s.rationale}</p></div>)}{!data.detail?.sessions.length&&<p className="text-sm text-slate-400">{t("لا توجد جلسات مسجلة","No sessions recorded")}</p>}</div></div><div className="rounded-3xl border bg-white p-5"><h2 className="font-semibold text-purple-950">{t("توثيق قرار الجلسة","Document session decision")}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div><Label>{t("الجهاز الذي اختاره الطبيب","Physician-selected device")}</Label><Select value={session.deviceType} onValueChange={v=>setSession({...session,deviceType:v})}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Accure">Accure</SelectItem><SelectItem value="Pico">Pico</SelectItem><SelectItem value="Fractional">Fractional</SelectItem></SelectContent></Select></div><Field label={t("مبرر الاختيار","Clinical rationale")} value={session.rationale} onChange={v=>setSession({...session,rationale:v})}/><Field label={t("الإعدادات المستخدمة","Parameters")} value={session.parameters} onChange={v=>setSession({...session,parameters:v})}/><Field label={t("الاستجابة والملاحظات","Response and observations")} value={session.responseNotes} onChange={v=>setSession({...session,responseNotes:v})}/></div><Button className="mt-4 w-full bg-purple-950" onClick={()=>act({action:"session_complete",patientId:patient.id,journeyId,sessionNumber:Number(patient.completed_sessions||0)+1,...session},t("تم توثيق الجلسة","Session documented"))}><Camera/>{t("إكمال الجلسة وتوثيقها","Complete & document session")}</Button></div></section></TabsContent>
 <TabsContent value="daily" className="mt-4"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-semibold text-purple-950">{t("قرار المراجعة اليومية","Daily review decision")}</h2><p className="mt-1 text-sm text-slate-500">{t("كل مريض يبقى ظاهرًا؛ الحالات الخطرة تُرتّب أولًا ولا تخفي الباقين.","Every patient remains visible; higher-risk cases are prioritized, not isolated.")}</p><div className="mt-5 grid gap-4 md:grid-cols-[.6fr_1.4fr]"><div><Label>{t("الإجراء","Action")}</Label><Select value={decision.decision} onValueChange={v=>setDecision({...decision,decision:v})}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no_change">No change</SelectItem><SelectItem value="personal_message">Send personal message</SelectItem><SelectItem value="modify_instructions">Modify instructions</SelectItem><SelectItem value="recall_early">Recall early</SelectItem></SelectContent></Select></div><Field label={t("المبرر السريري","Clinical rationale")} value={decision.rationale} onChange={v=>setDecision({...decision,rationale:v})}/></div><Button className="mt-4 bg-purple-950" onClick={()=>act({action:"daily_decision",patientId:patient.id,journeyId,...decision},t("تم توثيق القرار","Decision documented"))}>{t("توثيق القرار","Document decision")}</Button><div className="mt-6 space-y-3">{data.detail?.decisions.map(d=><div key={String(d.id)} className="rounded-2xl border p-4"><div className="flex justify-between"><span className="font-medium">{String(d.decision).replaceAll("_"," ")}</span><span className="text-xs text-slate-400">{new Date(String(d.effective_at)).toLocaleString(arabic?"ar-JO":"en-GB")}</span></div><p className="mt-2 text-sm text-slate-500">{d.rationale}</p></div>)}</div></section></TabsContent>
 <TabsContent value="alerts" className="mt-4"><section className="rounded-3xl border bg-white p-5"><h2 className="font-semibold text-purple-950">{t("تنبيهات المريض","Patient alerts")}</h2><div className="mt-4 space-y-3">{data.alerts.map(a=><div key={String(a.id)} className={`rounded-2xl border p-4 ${a.severity==="high"?"border-rose-200 bg-rose-50":""}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-medium">{String(a.rule_key).replaceAll("_"," ")}</div><div className="mt-1 text-sm text-slate-500">{a.severity} · {a.status}</div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>act({action:"alert_update",patientId:patient.id,journeyId,alertId:a.id,status:"acknowledged"},t("تم استلام التنبيه","Alert acknowledged"))}>{t("استلام","Acknowledge")}</Button><Button size="sm" onClick={()=>act({action:"alert_update",patientId:patient.id,journeyId,alertId:a.id,status:"resolved",resolution:"Physician reviewed"},t("تم إغلاق التنبيه","Alert resolved"))}>{t("إغلاق","Resolve")}</Button></div></div></div>)}{!data.alerts.length&&<div className="rounded-2xl bg-slate-50 p-8 text-center text-slate-400">{t("لا توجد تنبيهات مفتوحة","No open alerts")}</div>}</div></section></TabsContent>
 <TabsContent value="outcome" className="mt-4"><section className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-purple-950">{t("اعتماد وثيقة النتيجة","Finalize outcome evidence")}</h2><p className="mt-1 text-sm text-slate-500">{t("يُبنى خط الأساس والقياس النهائي فقط من القياسات المعتمدة، ثم يضيف الطبيب تفسيره.","Baseline and final values use approved measures only; the physician adds the interpretation.")}</p></div><Badge variant="outline">{data.detail?.metrics.filter(m=>m.review_state==="approved").length||0} {t("قياسات معتمدة","approved measures")}</Badge></div><div className="mt-6 grid gap-3 md:grid-cols-3">{[...new Set((data.detail?.metrics||[]).filter(m=>m.review_state==="approved").map(m=>String(m.metric)))].map(metric=>{const rows=(data.detail?.metrics||[]).filter(m=>m.metric===metric&&m.review_state==="approved");return <div key={metric} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{metric}</div><div className="mt-2 font-semibold text-purple-950">{rows[0]?.value??"—"} → {rows.at(-1)?.value??"—"}</div></div>})}</div><Label className="mt-6 block">{t("تفسير الطبيب والقيود","Physician interpretation and limitations")}</Label><Textarea className="mt-2 min-h-32" value={outcomeConclusion} onChange={e=>setOutcomeConclusion(e.target.value)} placeholder={t("وثّق النتيجة في سياق الاستجابة والالتزام، دون ضمانات أو ادعاءات غير مدعومة.","Document the outcome in context of response and adherence, without guarantees or unsupported claims.")}/><Button className="mt-4 bg-purple-950" disabled={!outcomeConclusion.trim()} onClick={()=>act({action:"outcome_finalize",patientId:patient.id,journeyId,physicianConclusion:outcomeConclusion},t("تم اعتماد وثيقة النتيجة","Outcome evidence finalized"))}><FileCheck2/>{t("اعتماد وثيقة النتيجة","Finalize outcome")}</Button></section></TabsContent>
 <TabsContent value="templates" className="mt-4"><section className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-purple-950">{t("القوالب والبروتوكولات","Templates and protocols")}</h2><p className="mt-1 text-sm text-slate-500">{t("لا يظهر في العلاج إلا الإصدار المنشور المعتمد.","Only approved published versions are used in care.")}</p></div><ShieldCheck className="text-purple-700"/></div><div className="mt-5 space-y-3">{data.templates.map(c=><div key={String(c.id)} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><div className="font-medium">{String(c.config_key).replaceAll("_"," ")}</div><div className="mt-1 text-sm text-slate-400">v{c.version} · {c.status}</div></div><div className="flex items-center gap-2"><Badge className={c.status==="published"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}>{c.status}</Badge>{c.status==="draft"&&data.roles?.some(r=>["medical_director","super_admin"].includes(r))&&<Button size="sm" onClick={()=>act({action:"template_approve",configId:c.id,requestedBy:c.owner_id,reason:"Reviewed and approved by Medical Director"},t("تم اعتماد الإصدار","Version approved"))}>{t("اعتماد ونشر","Approve & publish")}</Button>}</div></div>)}</div></section></TabsContent></Tabs>}</section></div></main>;
}

function jsonText(value:unknown){try{return String(JSON.parse(String(value||"{}")).text||"")}catch{return ""}}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-400">{label}</div><div className="mt-1 text-sm text-slate-700">{value}</div></div>}
function Meter({label,value}:{label:string;value:number}){return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span>{value}%</span></div><Progress value={value}/></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label>{label}</Label><Textarea value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-24"/></div>}
