"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {intakeOptions,viewTypes,type IntakeData} from "@/lib/intake-options";
type Doc={id:string;kind:string;view_type:string;filename:string;mime:string;created_at:string};
const labels:Record<string,[string,string]>={residence:["الإقامة","Residence"],city:["مدينة الإقامة","City"],travel:["هل يوجد سفر مخطط؟","Planned travel?"],goal:["الهدف العلاجي","Treatment goal"],effects:["الآثار محل الاهتمام","Concerns"],medications:["هل يستخدم أدوية؟","Current medications?"],medicationTypes:["الأدوية الحالية — اختيار متعدد","Medication categories — multiple selection"],duration:["مدة الاستخدام","Duration"],dose:["تكرار الاستخدام — تفاصيل الجرعة يراجعها الطبيب","Frequency — clinician to clarify exact dose"],otherTreatments:["هل يخضع لعلاجات أخرى؟","Other treatments?"],treatmentTypes:["العلاجات الأخرى — اختيار متعدد","Other treatments — multiple selection"],lastTreatment:["آخر جلسة","Last session"]};
export default function IntakeAssessment({patientId,arabic,readOnly=false}:{patientId:string;arabic:boolean;readOnly?:boolean}){
 const t=(a:string,b:string)=>arabic?a:b;
 const [data,setData]=useState<IntakeData>({}),[version,setVersion]=useState(0),[docs,setDocs]=useState<Doc[]>([]),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState(0),[view,setView]=useState(""),[selected,setSelected]=useState("");
 const endpoint=`/api/intake?patientId=${encodeURIComponent(patientId)}`;
 const url=(id:string)=>`${endpoint}&documentId=${encodeURIComponent(id)}`;
 const load=async()=>{setError("");setReady(false);try{const r=await fetch(endpoint,{cache:"no-store"});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b.data);setVersion(b.version);setDocs(b.documents);setReady(true);}catch{setError(t("تعذر تحميل التقييم. تأكد من تطبيق تحديث قاعدة البيانات ثم أعد المحاولة.","Could not load assessment. Apply the database migration and retry."));}};
 useEffect(()=>{setData({});setDocs([]);setSelected("");void load();},[patientId]);
 const change=(key:string,value:string|string[])=>{setData(d=>({...d,[key]:value}));setNotice("");};
 const save=async()=>{setBusy(true);setError("");try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data,version})});const b=await r.json();if(!r.ok)throw Error(b.error);setVersion(b.version);setNotice(t("تم حفظ البيانات. إيميل التواصل لا يفعّل حساب الدخول تلقائيًا.","Saved. Contact email does not automatically provision a login account."));}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}};
 const upload=async(files:FileList|null,kind:string)=>{if(!files?.length)return;setBusy(true);setError("");let uploaded=0;try{for(const file of Array.from(files)){const body=new FormData();body.set("file",file);body.set("kind",kind);body.set("view",view);const r=await fetch(endpoint,{method:"POST",body});const b=await r.json();if(!r.ok)throw Error(`${file.name}: ${b.error}`);uploaded++;}setNotice(t(`تم رفع ${uploaded} ملف. التقرير لم تتم مراجعته طبيًا بعد.`,`${uploaded} files uploaded. Report awaits clinical review.`));}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{try{const r=await fetch(endpoint,{cache:"no-store"});if(r.ok)setDocs((await r.json()).documents);}finally{setBusy(false);}}};
 const select=(key:keyof typeof intakeOptions,multiple=false)=> <label key={key} className="grid gap-2 text-sm"><span className="font-medium">{labels[key][arabic?0:1]}</span><select disabled={readOnly||busy} multiple={multiple} size={multiple?4:undefined} className="w-full rounded-xl border bg-white p-3" value={multiple?(Array.isArray(data[key])?data[key]:[]):String(data[key]||"")} onChange={e=>change(key,multiple?Array.from(e.target.selectedOptions,o=>o.value):e.target.value)}>{!multiple&&<option value="">{t("اختر…","Select…")}</option>}{intakeOptions[key].map(o=><option key={o} value={o}>{o.split(" / ")[arabic?0:1]||o}</option>)}</select>{multiple&&<span className="text-xs text-slate-500">{t("يمكن اختيار أكثر من عنصر؛ على الكمبيوتر استخدم Ctrl أو ⌘.","Select multiple; use Ctrl or ⌘ on desktop.")}</span>}</label>;
 const images=docs.filter(d=>d.kind==='image'),reports=docs.filter(d=>d.kind==='report');
 const status=!(data.birthDate&&data.residence&&data.travel&&data.goal&&data.medications&&data.otherTreatments&&images.length)?t("التقييم الأولي غير مكتمل","Initial assessment incomplete"):t("بانتظار مراجعة الطبيب","Awaiting physician review");
 const image=images.find(d=>d.id===selected)||images[0];
 return <section dir={arabic?'rtl':'ltr'} className="space-y-5 rounded-3xl border bg-white p-4 md:p-6">
 <header><p className="mb-2 text-sm font-medium text-purple-700">{status}</p><h2 className="text-xl font-semibold text-purple-950">{t("جواز سفر البشرة · التقييم الأولي","Skin passport · Initial assessment")}</h2><p className="mt-2 text-sm text-slate-500">{t("البرنامج يحدده الطبيب بعد التقييم. الربط الآلي بالذكاء الاصطناعي لم يُفعّل بعد.","Program selection follows clinical assessment. Automated AI integration is not connected.")}</p></header>
 {error&&<div role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-800">{error} <Button variant="outline" disabled={busy} onClick={load}>{t("إعادة تحميل","Reload")}</Button></div>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
 {!ready&&!error&&<p>{t("جارٍ تحميل الملف…","Loading record…")}</p>}
 {ready&&<><nav className="flex flex-wrap gap-2" aria-label={t("خطوات التقييم","Assessment steps")}>{[["البيانات الشخصية","Personal details"],["بيانات الاستقبال","Intake history"],["الصور والتقرير والسكورينج","Images, report & scores"]].map((l,i)=><Button key={i} variant={tab===i?'default':'outline'} onClick={()=>setTab(i)}>{i+1}. {l[arabic?0:1]}</Button>)}</nav>
 {tab===0&&<div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2">{t("إيميل التواصل","Contact email")}<Input disabled={readOnly||busy} type="email" dir="ltr" value={String(data.email||"")} onChange={e=>change('email',e.target.value)}/></label><label className="grid gap-2">{t("تاريخ الميلاد","Birth date")}<Input disabled={readOnly||busy} type="date" max={new Date().toISOString().slice(0,10)} value={String(data.birthDate||"")} onChange={e=>change('birthDate',e.target.value)}/></label><p className="text-sm text-slate-500 md:col-span-2">{t("الاسم والموبايل محفوظان في السجل الأساسي. هذا التقييم مرتبط بنفس رقم الملف.","Name and mobile are held in the core record. This assessment uses the same patient ID.")}</p></div>}
 {tab===1&&<div className="grid gap-4 md:grid-cols-2">{select('residence')}{select('city')}{select('travel')}{String(data.travel).startsWith('نعم')&&<fieldset className="space-y-2"><legend>{t("موعد السفر المتوقع — اتركه فارغًا إذا لم يتحدد","Expected travel — leave blank if unknown")}</legend><div className="flex gap-2">{[['travelDay',31,'اليوم / Day'],['travelMonth',12,'الشهر / Month'],['travelYear',10,'السنة / Year']].map(([k,n,l])=><select aria-label={String(l)} disabled={readOnly||busy} className="min-w-0 flex-1 rounded-xl border p-2" key={k} value={String(data[k]||'')} onChange={e=>change(String(k),e.target.value)}><option value="">{l}</option>{Array.from({length:Number(n)},(_,i)=>k==='travelYear'?new Date().getFullYear()+i:i+1).map(v=><option key={v}>{v}</option>)}</select>)}</div></fieldset>}{select('goal')}{String(data.goal).startsWith('حب الشباب وآثاره')&&select('effects',true)}{select('medications')}{String(data.medications).startsWith('نعم')&&<>{select('medicationTypes',true)}{select('duration')}{select('dose')}</>}{select('otherTreatments')}{String(data.otherTreatments).startsWith('نعم')&&<>{select('treatmentTypes',true)}{select('lastTreatment')}</>}</div>}
 {tab===2&&<div className="space-y-5">{!readOnly&&<><label className="flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm"><input type="checkbox" disabled={busy} checked={data.consent==='yes'} onChange={e=>change('consent',e.target.checked?'yes':'no')}/>{t("أؤكد توثيق موافقة المريض على حفظ صور البشرة والتقرير في ملفه. لا يتم إرسال الصور لخدمة AI في هذه النسخة.","I confirm the patient's consent to store skin images and the report. This release does not send images to an AI service.")}</label><p className="text-sm text-slate-500">{t("احفظ الموافقة قبل رفع الملفات. حتى ٢٠ ملفًا، بحد ١٠ ميجابايت للملف؛ JPEG / PNG وصيغة PDF للتقرير.","Save consent before uploading. Up to 20 files, 10 MB each; JPEG / PNG and PDF reports.")}</p><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2">{t("نوع صور OBSERV التي سترفعها","OBSERV view for this upload")}<select disabled={busy} className="rounded-xl border p-3" value={view} onChange={e=>setView(e.target.value)}><option value="">{t("اختر النوع","Select view")}</option>{viewTypes.map(v=><option key={v}>{v}</option>)}</select><input aria-label="Upload OBSERV images" type="file" accept="image/jpeg,image/png" multiple disabled={busy||!view||data.consent!=='yes'} onChange={e=>{void upload(e.target.files,'image');e.target.value='';}}/></label><label className="grid gap-2">{t("رفع تقرير التقييم الأصلي","Upload original assessment report")}<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy||data.consent!=='yes'} onChange={e=>{void upload(e.target.files,'report');e.target.value='';}}/></label></div></>}
 <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-3"><h3 className="mb-3 font-semibold">{t("صور البشرة","Skin images")}</h3>{image?<><a href={url(image.id)} target="_blank" rel="noreferrer"><img alt={image.view_type} className="h-80 w-full rounded-xl object-contain" src={url(image.id)}/></a><p className="my-2 text-xs">{image.view_type} · {new Date(image.created_at).toLocaleString()} · {t("تاريخ الرفع — اضغط للتكبير","Upload date — click to enlarge")}</p><div className="flex flex-wrap gap-2">{images.map(d=><button aria-label={d.view_type} key={d.id} onClick={()=>setSelected(d.id)} className="rounded-lg border p-1"><img loading="lazy" alt={d.view_type} className="h-16 w-16 object-cover" src={url(d.id)}/></button>)}</div></>:<p className="py-16 text-center text-slate-500">{t("لم تُرفع صور بعد","No images uploaded")}</p>}</div><div className="rounded-2xl border p-3"><h3 className="font-semibold">{t("تقرير التقييم المرفوع — بانتظار مراجعة الطبيب","Uploaded assessment — awaiting physician review")}</h3>{!reports.length&&<p className="py-16 text-center text-slate-500">{t("لم يُرفع تقرير بعد","No report uploaded")}</p>}{reports.map(d=><div key={d.id} className="mt-3 space-y-2"><a className="text-purple-700 underline" href={url(d.id)} target="_blank" rel="noreferrer">{d.filename} ↗</a>{d.mime==='application/pdf'?<object aria-label="Assessment PDF" data={url(d.id)} type="application/pdf" className="h-80 w-full"><a href={url(d.id)} target="_blank" rel="noreferrer">{t("فتح التقرير","Open report")}</a></object>:<img alt={d.filename} className="max-h-96 w-full object-contain" src={url(d.id)}/>}</div>)}</div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['نشاط حب الشباب','Acne activity'],['الاحمرار','Redness'],['التصبغات','Pigmentation'],['الملمس','Texture'],['الندبات','Scarring']].map(l=><div key={l[1]} className="rounded-xl border p-4"><h4 className="text-sm">{l[arabic?0:1]}</h4><div className="my-2 text-2xl">—</div><p className="text-xs text-slate-500">{t("غير متاح — لم يتم الربط","Unavailable — not connected")}</p></div>)}</div><p className="text-sm text-slate-500">{t("رفع التقرير لا يستخرج الدرجات تلقائيًا ولا يعتمدها. يراجع الطبيب القيم في التقرير الأصلي حتى تفعيل التكامل.","Uploading a report does not extract or approve scores. Clinicians review the original report until integration is enabled.")}</p></div>}
 {!readOnly&&<footer className="flex items-center gap-3 border-t pt-4"><Button disabled={busy} onClick={save}>{busy?t("جارٍ الحفظ أو الرفع…","Saving / uploading…"):t("حفظ بيانات التقييم","Save assessment")}</Button><span className="text-xs text-slate-500">{t("يمكن الحفظ والمتابعة لاحقًا","Save and resume later")}</span></footer>}</>}
 </section>;
}
