"use client";
import {useCallback,useEffect,useState} from "react";
import {Check,Database,KeyRound,Link2,RefreshCw,ShieldCheck,TriangleAlert,Webhook} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {toast} from "sonner";
type Row=Record<string,any>;type Data={integrations:Row[];jobs:Row[];checks:Row};
export default function IntegrationsCenter({arabic}:{arabic:boolean}){const t=(ar:string,en:string)=>arabic?ar:en;const [data,setData]=useState<Data>({integrations:[],jobs:[],checks:{}}),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);const r=await fetch("/api/integrations/status",{cache:"no-store"});const b=await r.json();if(r.ok)setData(b);else toast.error(b.error||t("تعذر فحص التكاملات","Could not check integrations"));setLoading(false)},[arabic]);useEffect(()=>{void load()},[load]);const test=async(provider:string)=>{const r=await fetch("/api/integrations/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"test_connection",provider})});const b=await r.json();if(r.ok)toast.success(t("بيانات الاتصال متاحة","Connection configuration is available"));else toast.error(b.error||t("بيانات الاعتماد غير مكتملة","Credentials are incomplete"));await load()};const passed=Object.values(data.checks).filter(Boolean).length,total=Object.keys(data.checks).length;
 return <section><div className="mb-5 flex flex-wrap items-end justify-between gap-4 rounded-3xl bg-purple-950 p-6 text-white"><div><div className="flex items-center gap-2 text-sm font-semibold text-purple-200"><Link2 className="size-4"/>{t("جاهزية الإطلاق","GO-LIVE READINESS")}</div><h2 className="mt-2 text-2xl font-semibold">{t("الاختبارات والربط الخارجي","Final validation & integrations")}</h2><p className="mt-2 max-w-3xl text-sm text-purple-200">{t("يتم عرض الحالة الفعلية فقط؛ لا يُعتبر أي مزود متصلًا قبل إضافة بيانات الاعتماد واختبارها.","Only actual state is shown; no provider is considered connected before credentials are added and checked.")}</p></div><Button variant="outline" className="border-white/20 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={load}><RefreshCw className={loading?"animate-spin":""}/>{t("إعادة الفحص","Recheck")}</Button></div>
 <div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><section className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-semibold text-purple-950">{t("فحوصات المنصة","Platform checks")}</h3><Badge className={passed===total?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}>{passed}/{total}</Badge></div><div className="mt-5 space-y-3">{Object.entries(data.checks).map(([key,ok])=><div key={key} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm">{key.replaceAll("_"," ")}</span>{ok?<Check className="size-5 text-emerald-600"/>:<TriangleAlert className="size-5 text-amber-500"/>}</div>)}</div><div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm leading-6 text-emerald-900"><ShieldCheck className="mb-2 size-5"/>{t("الوصول الخاص، قاعدة البيانات، سجل التدقيق وحدود القرار السريري مفعّلة.","Private access, database, audit logging, and the clinical decision boundary are active.")}</div></section><section className="space-y-4">{data.integrations.map(x=><div key={x.provider} className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><div className={`grid size-12 place-items-center rounded-2xl ${x.configured?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{x.provider==="whatsapp"?<Webhook/>:x.provider==="haut_ai"?<Database/>:<Link2/>}</div><div><h3 className="font-semibold text-purple-950">{x.label}</h3><div className="mt-1 flex flex-wrap gap-2">{x.capabilities.map((c:string)=><Badge key={c} variant="outline">{c.replaceAll("_"," ")}</Badge>)}</div></div></div><div className="flex items-center gap-2"><Badge className={x.configured?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}>{x.configured?t("مهيأ","Configured"):t("ينتظر بيانات الاعتماد","Awaiting credentials")}</Badge><Button size="sm" variant="outline" onClick={()=>test(x.provider)}>{t("اختبار","Test")}</Button></div></div>{!x.configured&&<div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-sm font-medium text-slate-700"><KeyRound className="size-4"/>{t("المطلوب للتفعيل","Required to activate")}</div><div className="mt-2 flex flex-wrap gap-2">{x.missing.map((m:string)=><code key={m} className="rounded-lg bg-white px-2 py-1 text-xs text-slate-600">{m}</code>)}</div></div>}{x.runtime?.last_error&&<p className="mt-3 text-sm text-rose-600">{x.runtime.last_error}</p>}</div>)}</section></div>
 <section className="mt-5 rounded-3xl border bg-white p-5"><h3 className="font-semibold text-purple-950">{t("حدود التكامل السريري","Clinical integration boundary")}</h3><div className="mt-4 grid gap-3 md:grid-cols-3">{[[t("OBSERV 520x","OBSERV 520x"),t("نقل صور ومعرّف المريض فقط عبر الجسر المعتمد.","Transfers images and patient identity only through the approved bridge.")],[t("التحليل الآلي","Automated analysis"),t("تدخل النتائج بحالة: بانتظار مراجعة الطبيب.","Results enter as pending physician review.")],[t("الطبيب","Physician"),t("يعتمد القياسات ويفسرها ويتخذ القرار العلاجي.","Approves and interprets measures and makes treatment decisions.")]].map(([h,p])=><div key={h} className="rounded-2xl bg-slate-50 p-4"><div className="font-medium">{h}</div><p className="mt-2 text-sm leading-6 text-slate-500">{p}</p></div>)}</div></section></section>}
