"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,Bell,CalendarDays,Check,ChevronRight,Clock3,HeartPulse,Home,MessageCircle,Route,Send,Settings2,Sparkles,UserRound} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Progress} from "@/components/ui/progress";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Label} from "@/components/ui/label";
import {Switch} from "@/components/ui/switch";
import {toast,Toaster} from "sonner";

type Row=Record<string,any>;
type PortalData={patient:Row;journey?:Row;program?:Row;consultation?:Row;appointments:Row[];tasks:Row[];sessions:Row[];events:Row[];metrics:Row[];threads:Row[];messages:Row[];notifications:Row[];preferences?:Row;emergencyContact?:Row;marketingConsent?:Row;preview?:boolean};
const journeyLabels:Record<string,[string,string]>={REGISTERED:["تم التسجيل","Registered"],BASELINE_CAPTURED:["اكتمل خط الأساس","Baseline complete"],CONSULTATION_OPEN:["الاستشارة","Consultation"],PROGRAM_ACTIVE:["التحكم والعلاج","Control & treatment"],PROGRESS_REVIEW:["مراجعة التقدم","Progress review"],MAINTENANCE:["المحافظة","Maintenance"],COMPLETED:["اكتمل البرنامج","Program complete"]};
function parseText(value?:string){try{return JSON.parse(value||"{}").text||""}catch{return ""}}
function fmt(value:string|undefined,arabic:boolean){if(!value)return "—";return new Intl.DateTimeFormat(arabic?"ar-JO":"en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Amman"}).format(new Date(value))}

type PortalError="AUTHENTICATION_REQUIRED"|"SETUP_REQUIRED"|"PATIENT_NOT_FOUND"|"LOAD_FAILED";

export default function PatientPortal({arabic,onOpenAdmin}:{arabic:boolean;onOpenAdmin?:()=>void}){
 const t=(ar:string,en:string)=>arabic?ar:en;
 const [data,setData]=useState<PortalData|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState<PortalError|null>(null),[dialog,setDialog]=useState<"message"|"reschedule"|"checkin"|"settings"|null>(null),[busy,setBusy]=useState(false),[setupBusy,setSetupBusy]=useState(false);
 const [message,setMessage]=useState(""),[reason,setReason]=useState(""),[preferred,setPreferred]=useState(""),[rating,setRating]=useState(3),[notes,setNotes]=useState(""),[redFlag,setRedFlag]=useState(false),[morning,setMorning]=useState("08:00"),[evening,setEvening]=useState("20:00"),[meds,setMeds]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setLoadError(null);try{const res=await fetch("/api/patient/portal",{cache:"no-store"});const value=await res.json().catch(()=>({}));if(!res.ok){const code=String(value.error||"");setData(null);setLoadError(code==="AUTHENTICATION_REQUIRED"||code==="SETUP_REQUIRED"||code==="PATIENT_NOT_FOUND"?code:"LOAD_FAILED");return}setData(value);setMorning(value.preferences?.morning_time||"08:00");setEvening(value.preferences?.evening_time||"20:00");setMeds(value.preferences?.medication_opt_in!==0)}catch{setData(null);setLoadError("LOAD_FAILED")}finally{setLoading(false)}},[]);
 const initialize=async()=>{setSetupBusy(true);try{const res=await fetch("/api/setup",{method:"POST"});if(!res.ok)throw new Error();toast.success(t("تم تجهيز مساحة العمل","Workspace initialized"));await load();onOpenAdmin?.()}catch{toast.error(t("تعذر إتمام الإعداد. حاول مرة أخرى.","Setup could not be completed. Please try again."))}finally{setSetupBusy(false)}};
 useEffect(()=>{void load()},[load]);
 const act=async(action:string,payload:Row={})=>{if(!data)return;setBusy(true);const res=await fetch("/api/patient/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,patientId:data.patient.id,...payload})});const body=await res.json().catch(()=>({}));setBusy(false);if(!res.ok){toast.error(body.error||t("تعذر حفظ الإجراء","Action could not be saved"));return false}toast.success(t("تم الحفظ بنجاح","Saved successfully"));setDialog(null);await load();return true};
 const upcoming=data?.appointments.find(a=>a.status!=="cancelled"&&new Date(a.starts_at)>new Date());const done=data?.tasks.filter(x=>x.status==="done").length||0,total=data?.tasks.length||0;const progress=total?Math.round(done/total*100):Math.min(100,Math.round(((data?.journey?.completed_sessions||0)/(data?.journey?.session_target||9))*100));
 const programName=arabic?(data?.program?.name_ar||"Glow Up Acne"):(data?.program?.name_en||"Glow Up Acne");const state=journeyLabels[data?.journey?.current_state||"PROGRAM_ACTIVE"]||["البرنامج الفعّال","Active program"];
 const timeline=useMemo(()=>[{w:0,ar:"الاستشارة والخطة المنزلية",en:"Consultation & home care"},{w:1,ar:"جلسة Accure 1",en:"Accure session 1"},{w:3,ar:"Fractional / Pico 1",en:"Fractional / Pico 1"},{w:5,ar:"جلسة Accure 2",en:"Accure session 2"},{w:7,ar:"Fractional / Pico 2",en:"Fractional / Pico 2"},{w:9,ar:"جلسة Accure 3",en:"Accure session 3"},{w:11,ar:"Fractional / Pico 3",en:"Fractional / Pico 3"},{w:13,ar:"جلسة Accure 4",en:"Accure session 4"},{w:15,ar:"Fractional / Pico 4",en:"Fractional / Pico 4"},{w:19,ar:"Fractional / Pico 5",en:"Fractional / Pico 5"},{w:23,ar:"مراجعة ما بعد العلاج",en:"Post-treatment review"},{w:26,ar:"التقييم النهائي",en:"Final assessment"}],[]);
 if(loading)return <main className="mx-auto max-w-6xl p-6"><div className="h-52 animate-pulse rounded-[2rem] bg-purple-100"/></main>;
 if(!data){const content=loadError==="AUTHENTICATION_REQUIRED"?{title:t("انتهت جلسة الدخول","Your session has ended"),body:t("أعد فتح الموقع من حسابك المسجل ثم حاول مرة أخرى.","Open the site again from your signed-in account, then retry."),action:t("إعادة المحاولة","Try again")} : loadError==="SETUP_REQUIRED"?{title:t("يلزم تجهيز مساحة العمل أولًا","Workspace setup is required"),body:t("هذه نسخة جديدة ولم تُنشأ بيانات العيادة والصلاحيات بعد. يتم الإعداد مرة واحدة فقط.","This is a new workspace. Clinic data and permissions have not been initialized yet. Setup is required only once."),action:t("تجهيز مساحة العمل","Initialize workspace")} : loadError==="PATIENT_NOT_FOUND"?{title:t("لا يوجد ملف مريض متاح لهذا الحساب","No patient record is available for this account"),body:t("إذا كنت مريضًا، اطلب من الاستقبال ربط حسابك بملفك. وإذا كنت من الإدارة، أنشئ أول ملف مريض أو افتحه من لوحة الإدارة.","If you are a patient, ask reception to link your account to your record. If you are an administrator, create or open a patient from the admin workspace."),action:t("فتح لوحة الإدارة","Open admin workspace")} : {title:t("تعذر تحميل الملف الآن","The record could not be loaded"),body:t("قد يكون السبب اتصالًا مؤقتًا أو خطأ في الخادم. بياناتك لم تُحذف.","This may be a temporary connection or server error. Your data has not been deleted."),action:t("إعادة المحاولة","Try again")};return <main className="mx-auto max-w-3xl p-6 sm:p-8"><Toaster richColors/><section className="rounded-[2rem] border border-amber-200 bg-white p-8 text-center shadow-sm sm:p-12"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-amber-50"><AlertTriangle className="text-amber-600"/></div><h1 className="mt-5 text-xl font-semibold text-purple-950">{content.title}</h1><p className="mx-auto mt-3 max-w-xl text-base leading-7 text-slate-600">{content.body}</p><div className="mt-7 flex flex-wrap justify-center gap-3">{loadError==="SETUP_REQUIRED"?<Button disabled={setupBusy} onClick={()=>void initialize()} className="bg-purple-950 hover:bg-purple-900">{setupBusy?t("جارٍ التجهيز…","Initializing…"):content.action}</Button>:loadError==="PATIENT_NOT_FOUND"&&onOpenAdmin?<Button onClick={onOpenAdmin} className="bg-purple-950 hover:bg-purple-900">{content.action}</Button>:<Button onClick={()=>void load()} className="bg-purple-950 hover:bg-purple-900">{content.action}</Button>}{loadError!=="SETUP_REQUIRED"&&loadError!=="LOAD_FAILED"&&<Button variant="outline" onClick={()=>void load()}>{t("تحديث الحالة","Refresh status")}</Button>}</div></section></main>}
 const name=arabic?(data.patient.full_name_ar||data.patient.full_name_en):(data.patient.full_name_en||data.patient.full_name_ar);const initials=String(name||"DG").split(" ").map((x:string)=>x[0]).slice(0,2).join("");
 return <main dir={arabic?"rtl":"ltr"} className="mx-auto max-w-[1380px] px-4 pb-28 pt-6 sm:px-6 lg:px-8"><Toaster richColors/>
  {data.preview&&<div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{t("أنت تستعرض تجربة المريض بصلاحية الإدارة. كل إجراء يُسجل في سجل التدقيق.","You are previewing the patient experience as an administrator. Every action is audited.")}</div>}
  <section className="overflow-hidden rounded-[2rem] bg-[#30204d] text-white shadow-xl"><div className="grid gap-7 p-6 md:grid-cols-[1.2fr_.8fr] md:p-8"><div><div className="flex items-center gap-3"><div className="grid size-14 place-items-center rounded-2xl bg-white/12 text-lg font-semibold">{initials}</div><div><div className="text-sm text-purple-200">{t("جواز البشرة الرقمي","Digital Skin Passport")}</div><h1 className="text-2xl font-semibold">{t("مرحبًا، ","Welcome, ")}{name}</h1></div></div><div className="mt-8 flex flex-wrap items-end gap-8"><div><div className="text-sm text-purple-200">{t("مرحلتك الآن","Your current stage")}</div><div className="mt-1 text-xl font-semibold">{arabic?state[0]:state[1]}</div></div><div><div className="text-sm text-purple-200">{t("البرنامج","Program")}</div><div className="mt-1 text-lg font-medium">{programName}</div></div></div></div><div className="rounded-3xl bg-white/10 p-5"><div className="flex justify-between text-sm"><span>{t("تقدم الرحلة","Journey progress")}</span><strong>{progress}%</strong></div><Progress value={progress} className="mt-3 bg-white/15"/><div className="mt-5 flex gap-2"><Button onClick={()=>setDialog("checkin")} className="flex-1 bg-amber-400 text-purple-950 hover:bg-amber-300"><HeartPulse/>{t("فحص اليوم","Today’s check-in")}</Button><Button onClick={()=>setDialog("message")} variant="outline" className="border-white/20 bg-transparent text-white hover:bg-white/10 hover:text-white"><MessageCircle/></Button></div></div></div></section>
  <Tabs defaultValue="home" className="mt-6"><TabsList className="hidden h-auto w-full justify-start gap-1 overflow-x-auto rounded-2xl border bg-white p-2 md:flex"><TabsTrigger value="home"><Home/>{t("الرئيسية","Home")}</TabsTrigger><TabsTrigger value="journey"><Route/>{t("رحلتي","Journey")}</TabsTrigger><TabsTrigger value="program"><Sparkles/>{t("برنامجي","Program")}</TabsTrigger><TabsTrigger value="progress"><Activity/>{t("التقدم","Progress")}</TabsTrigger><TabsTrigger value="messages"><MessageCircle/>{t("الرسائل","Messages")}</TabsTrigger><TabsTrigger value="profile"><UserRound/>{t("الملف","Profile")}</TabsTrigger></TabsList>
   <TabsContent value="home" className="mt-5"><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-[2rem] border bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="text-sm font-medium text-purple-700">{t("مهمتك التالية","YOUR NEXT STEP")}</div><h2 className="mt-1 text-xl font-semibold text-purple-950">{data.tasks.find(x=>x.status==="pending")?.[arabic?"title_ar":"title_en"]||t("أكملي فحص اليوم","Complete today’s check-in")}</h2></div><Clock3 className="text-purple-500"/></div><div className="mt-5 space-y-3">{data.tasks.filter(x=>x.status==="pending").slice(0,3).map(task=><div key={task.id} className="flex flex-wrap items-center gap-3 rounded-2xl bg-slate-50 p-4"><div className="flex-1"><div className="font-medium">{task[arabic?"title_ar":"title_en"]}</div><div className="mt-1 text-sm text-slate-500">{task.period==="morning"?t("روتين الصباح","Morning routine"):t("روتين المساء","Evening routine")}</div></div><Button size="sm" disabled={busy} onClick={()=>act("task_complete",{taskId:task.id})}><Check/>{t("تم","Done")}</Button><Button size="sm" variant="ghost" onClick={()=>{const r=prompt(t("سبب التخطي","Reason for skipping"));if(r)void act("task_skip",{taskId:task.id,reason:r})}}>{t("تخطي","Skip")}</Button></div>)}</div></section><section className="rounded-[2rem] border bg-white p-5 sm:p-6"><div className="flex items-center gap-2 font-semibold text-purple-950"><CalendarDays className="text-purple-600"/>{t("الموعد القادم","Next appointment")}</div>{upcoming?<><div className="mt-5 text-lg font-semibold">{upcoming.service_name}</div><div className="mt-2 text-sm text-slate-500">{fmt(upcoming.starts_at,arabic)}</div><Badge className="mt-3 bg-emerald-50 text-emerald-700">{upcoming.status}</Badge><Button variant="outline" className="mt-5 w-full" onClick={()=>setDialog("reschedule")}>{t("طلب تغيير الموعد","Request reschedule")}</Button></>:<p className="mt-5 text-sm text-slate-500">{t("لا يوجد موعد قادم حاليًا","No upcoming appointment")}</p>}</section></div>{data.notifications?.length>0&&<section className="mt-5 rounded-[2rem] border bg-white p-5 sm:p-6"><div className="flex items-center gap-2 font-semibold text-purple-950"><Bell className="text-purple-600"/>{t("تذكيرات من فريق الرعاية","Care-team reminders")}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.notifications.slice(0,4).map(n=><div key={n.id} className="rounded-2xl bg-purple-50 p-4"><p className="text-sm leading-6 text-purple-950">{n.body}</p><div className="mt-2 text-xs text-purple-500">{fmt(n.sent_at||n.scheduled_for,arabic)}</div></div>)}</div></section>}</TabsContent>
   <TabsContent value="journey" className="mt-5"><section className="rounded-[2rem] border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold text-purple-950">{t("خطة الستة أشهر","Your six-month journey")}</h2><p className="mt-2 text-sm text-slate-500">{t("الخطة المعروضة إرشادية وتتغير فقط بقرار الطبيب حسب الاستجابة.","This roadmap is adjusted only by your physician according to response.")}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{timeline.map((item,i)=><div key={item.w} className={`flex items-center gap-4 rounded-2xl border p-4 ${i<(data.journey?.completed_sessions||0)?"border-emerald-200 bg-emerald-50":""}`}><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-purple-100 font-semibold text-purple-800">{item.w}</div><div className="flex-1"><div className="font-medium">{arabic?item.ar:item.en}</div><div className="text-sm text-slate-500">{t("الأسبوع","Week")} {item.w}</div></div>{i<(data.journey?.completed_sessions||0)&&<Check className="text-emerald-600"/>}</div>)}</div></section></TabsContent>
   <TabsContent value="program" className="mt-5"><div className="grid gap-5 lg:grid-cols-3">{[[t("روتين الصباح","Morning routine"),parseText(data.consultation?.routine_json)],[t("الأدوية الموصوفة","Prescribed medication"),parseText(data.consultation?.medication_json)],[t("تعليمات الطبيب","Physician instructions"),parseText(data.consultation?.instructions_json)]].map(([title,body])=><section key={title} className="rounded-[2rem] border bg-white p-6"><h2 className="font-semibold text-purple-950">{title}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{body||t("بانتظار اعتماد الطبيب","Awaiting physician approval")}</p></section>)}</div><section className="mt-5 rounded-[2rem] border bg-white p-6"><div className="flex justify-between"><h2 className="font-semibold text-purple-950">{t("التذكيرات","Reminders")}</h2><Button variant="outline" size="sm" onClick={()=>setDialog("settings")}><Settings2/>{t("تعديل","Edit")}</Button></div><div className="mt-4 flex flex-wrap gap-3 text-sm"><Badge variant="outline">{t("الصباح","Morning")} {morning}</Badge><Badge variant="outline">{t("المساء","Evening")} {evening}</Badge><Badge variant="outline">Asia/Amman</Badge></div></section></TabsContent>
   <TabsContent value="progress" className="mt-5"><section className="rounded-[2rem] border bg-white p-6"><h2 className="text-xl font-semibold text-purple-950">{t("تقدم متعدد الأبعاد","Multidimensional progress")}</h2><p className="mt-2 text-sm text-slate-500">{t("لا يوجد رقم واحد يختصر بشرتك. نعرض فقط القياسات التي راجعها الطبيب.","No single score defines your skin. Only physician-reviewed measures are shown.")}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{["Redness","Pigmentation","Texture","Scarring","Skin Condition"].map(metric=>{const rows=data.metrics.filter(x=>String(x.metric).toLowerCase().includes(metric.toLowerCase().split(" ")[0]));const last=rows.at(-1);return <div key={metric} className="rounded-2xl bg-slate-50 p-5"><div className="text-sm text-slate-500">{metric}</div><div className="mt-2 text-2xl font-semibold text-purple-950">{last?.value??"—"}{last&&<span className="text-sm text-slate-400">/100</span>}</div><div className="mt-2 text-xs text-emerald-700">{last?t("معتمد من الطبيب","Physician approved"):t("بانتظار القياس","Awaiting measure")}</div></div>})}</div></section></TabsContent>
   <TabsContent value="messages" className="mt-5"><section className="rounded-[2rem] border bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold text-purple-950">{t("فريق الرعاية","Care team")}</h2><p className="mt-1 text-sm text-slate-500">{t("عادةً يرد الفريق خلال ساعات العمل. للطوارئ اتصل بخدمات الطوارئ.","The team usually replies during clinic hours. For emergencies, contact emergency services.")}</p></div><Button onClick={()=>setDialog("message")}><Send/>{t("رسالة جديدة","New message")}</Button></div><div className="mt-6 space-y-3">{data.messages.length?data.messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-4 ${m.sender_role==="patient"?"ms-auto bg-purple-950 text-white":"bg-slate-100"}`}><p className="text-sm leading-6">{m.body}</p><div className={`mt-2 text-xs ${m.sender_role==="patient"?"text-purple-200":"text-slate-400"}`}>{fmt(m.sent_at,arabic)} · {m.delivery_status}</div></div>):<p className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">{t("ابدأ محادثة آمنة مع فريق الرعاية","Start a secure conversation with your care team")}</p>}</div></section></TabsContent>
   <TabsContent value="profile" className="mt-5"><div className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><section className="rounded-[2rem] border bg-white p-6"><div className="flex items-center gap-4"><div className="grid size-20 place-items-center rounded-full bg-purple-100 text-xl font-semibold text-purple-950">{initials}</div><div><h2 className="text-xl font-semibold">{name}</h2><p className="text-sm text-slate-500">{data.patient.reference_code}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[[t("تاريخ الميلاد","Date of birth"),data.patient.date_of_birth],[t("الهاتف","Mobile"),data.patient.mobile],[t("الفرع","Clinic"),data.patient.clinic_name],[t("الطبيب","Physician"),data.consultation?.physician_name||"—"]].map(([k,v])=><div key={k} className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{k}</div><div className="mt-1 font-medium">{v||"—"}</div></div>)}</div></section><section className="rounded-[2rem] border bg-white p-6"><h2 className="font-semibold text-purple-950">{t("البرنامج الفعّال","Active program")}</h2><div className="mt-4 rounded-2xl bg-purple-50 p-5"><div className="text-lg font-semibold text-purple-950">{programName}</div><div className="mt-2 text-sm text-purple-700">{arabic?state[0]:state[1]} · {t("بدأ","Started")} {data.program?.created_at?.slice(0,10)||"—"}</div></div><div className="mt-5"><div className="font-medium">{t("جهة اتصال للطوارئ","Emergency contact")}</div><div className="mt-2 text-sm text-slate-500">{data.emergencyContact?.name||"—"} · {data.emergencyContact?.mobile||"—"}</div></div><label className="mt-6 flex items-start justify-between gap-4 rounded-2xl border p-4"><span><span className="block font-medium">{t("موافقة التسويق المنفصلة","Separate marketing consent")}</span><span className="mt-1 block text-sm text-slate-500">{t("يمكن سحبها في أي وقت دون التأثير على الرعاية.","Withdraw anytime without affecting your care.")}</span></span><Switch checked={Boolean(data.marketingConsent?.granted)} onCheckedChange={v=>void act("marketing_consent",{granted:v})}/></label></section></div></TabsContent>
  
  <TabsList className="fixed inset-x-3 bottom-3 z-30 grid grid-cols-6 rounded-2xl border bg-white/95 p-2 shadow-2xl backdrop-blur md:hidden">{[["home",Home,t("الرئيسية","Home")],["journey",Route,t("الرحلة","Journey")],["program",Sparkles,t("البرنامج","Program")],["progress",Activity,t("التقدم","Progress")],["messages",MessageCircle,t("الرسائل","Messages")],["profile",UserRound,t("الملف","Profile")]].map(([value,Icon,label]:any)=><TabsTrigger key={value} value={value} className="flex-col gap-1 px-1 text-[11px]"><Icon className="size-4"/>{label}</TabsTrigger>)}</TabsList>
  </Tabs><Dialog open={dialog!==null} onOpenChange={v=>!v&&setDialog(null)}><DialogContent dir={arabic?"rtl":"ltr"}><DialogHeader><DialogTitle>{dialog==="message"?t("رسالة إلى فريق الرعاية","Message care team"):dialog==="reschedule"?t("طلب تغيير الموعد","Request reschedule"):dialog==="settings"?t("إعدادات التذكير","Reminder settings"):t("فحص اليوم","Today’s check-in")}</DialogTitle><DialogDescription>{dialog==="checkin"?t("هذا الفحص للمتابعة ولا يقدم تشخيصًا. عند الطوارئ اتصل بخدمات الطوارئ.","This check supports follow-up and is not a diagnosis. Contact emergency services for emergencies."):t("سيُحفظ طلبك في ملفك ويصل إلى الفريق.","Your request is saved to your record and sent to the team.")}</DialogDescription></DialogHeader>
   {dialog==="message"&&<div className="space-y-4"><Label>{t("رسالتك","Your message")}</Label><Textarea value={message} onChange={e=>setMessage(e.target.value)} className="min-h-28"/><Button className="w-full" disabled={busy||!message.trim()} onClick={()=>void act("send_message",{message,category:"care_question"}).then(ok=>ok&&setMessage(""))}><Send/>{t("إرسال","Send")}</Button></div>}
   {dialog==="reschedule"&&<div className="space-y-4"><Label>{t("الوقت المفضل","Preferred time")}</Label><Input type="datetime-local" value={preferred} onChange={e=>setPreferred(e.target.value)}/><Label>{t("السبب","Reason")}</Label><Textarea value={reason} onChange={e=>setReason(e.target.value)}/><Button className="w-full" disabled={busy||!preferred||!reason.trim()} onClick={()=>void act("request_reschedule",{appointmentId:upcoming?.id,preferredStartsAt:new Date(preferred).toISOString(),reason})}>{t("إرسال الطلب","Send request")}</Button></div>}
   {dialog==="checkin"&&<div className="space-y-5"><div><Label>{t("كيف حال بشرتك اليوم؟ 1–5","How is your skin today? 1–5")}</Label><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><Button key={n} variant={rating===n?"default":"outline"} onClick={()=>setRating(n)}>{n}</Button>)}</div></div><Label>{t("ملاحظات أو أعراض","Notes or symptoms")}</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/><label className="flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900"><span>{t("تورم شديد أو صعوبة تنفس أو عرض مقلق","Severe swelling, breathing difficulty, or concerning symptom")}</span><Switch checked={redFlag} onCheckedChange={setRedFlag}/></label><Button className="w-full" disabled={busy} onClick={()=>void act("submit_checkin",{rating,notes,redFlag,symptoms:notes?[notes]:[]})}>{t("إرسال الفحص","Submit check-in")}</Button></div>}
   {dialog==="settings"&&<div className="space-y-4"><Label>{t("تذكير الصباح","Morning reminder")}</Label><Input type="time" value={morning} onChange={e=>setMorning(e.target.value)}/><Label>{t("تذكير المساء","Evening reminder")}</Label><Input type="time" value={evening} onChange={e=>setEvening(e.target.value)}/><label className="flex items-center justify-between rounded-2xl border p-4"><span>{t("تذكيرات الدواء حسب وصف الطبيب","Medication reminders per physician prescription")}</span><Switch checked={meds} onCheckedChange={setMeds}/></label><Button className="w-full" disabled={busy} onClick={()=>void act("save_preferences",{morningTime:morning,eveningTime:evening,timezone:"Asia/Amman",medicationOptIn:meds,appointmentOptIn:true})}>{t("حفظ الإعدادات","Save settings")}</Button></div>}
  </DialogContent></Dialog>
 </main>
}
