"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Camera,RefreshCw,Upload,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import SkinReportDashboard from '@/app/skin-report-dashboard';
import {skinParameters,type SkinDraft} from '@/lib/skin-assessment';
type Report={id:string;document_id:string;status:string;created_at:string;error_code?:string;report:SkinDraft|null};
type Session={id:string;created_at:string;images:{id:string;angle:string;mode:string}[]};
type Data={baseline:Report|null;registration:Record<string,string|string[]>;registrationSnapshot:boolean;registrationUpdatedAt?:string;registrationDocuments:{id:string;kind:string;view_type:string;created_at:string}[];homeReports:Report[];sessions:Session[];preview:boolean;configured:boolean};
const fields:Record<string,[string,string]>={email:['البريد','Email'],birthDate:['تاريخ الميلاد','Birth date'],residence:['الإقامة','Residence'],city:['المدينة','City'],travel:['السفر','Travel'],travelDay:['يوم السفر','Travel day'],travelMonth:['شهر السفر','Travel month'],travelYear:['سنة السفر','Travel year'],goal:['الهدف','Goal'],effects:['الآثار','Sequelae'],medications:['أدوية حالية','Current medications'],medicationTypes:['أنواع الأدوية','Medication types'],duration:['مدة الاستخدام','Duration'],dose:['التكرار','Frequency'],otherTreatments:['علاجات أخرى','Other treatments'],treatmentTypes:['أنواع العلاجات','Treatment types'],lastTreatment:['آخر علاج','Last treatment']};
async function compactPhoto(file:Blob):Promise<File>{
 const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.88));if(!blob||blob.size>2*1024*1024)throw Error();return new File([blob],'home.jpg',{type:'image/jpeg'});}finally{URL.revokeObjectURL(url);}
}
export default function PatientSkin({patientId,arabic,preview}:{patientId:string;arabic:boolean;preview?:boolean}){
 const t=(ar:string,en:string)=>arabic?ar:en;const endpoint=`/api/patient/skin?patientId=${encodeURIComponent(patientId)}`;
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[step,setStep]=useState(0),[photos,setPhotos]=useState<(File|null)[]>([null,null,null]),[urls,setUrls]=useState<string[]>([]),[camera,setCamera]=useState(false),[cameraReady,setCameraReady]=useState(false),[storageConsent,setStorageConsent]=useState(false),[aiConsent,setAiConsent]=useState(false),[sessionId,setSessionId]=useState(''),[selected,setSelected]=useState('');
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);const readOnly=preview||data?.preview;
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(endpoint,{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b);}catch{setError(arabic?'تعذر تحميل التقييمات. اضغط تحديث.':'Could not load assessments. Please refresh.');}finally{setLoading(false)}},[endpoint,arabic]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const next=photos.map(p=>p?URL.createObjectURL(p):'');setUrls(next);return()=>next.forEach(u=>u&&URL.revokeObjectURL(u));},[photos]);
 useEffect(()=>{if(!camera)return;let disposed=false;setCameraReady(false);void navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1600},height:{ideal:1200}},audio:false}).then(s=>{if(disposed){s.getTracks().forEach(x=>x.stop());return;}stream.current=s;if(video.current){video.current.srcObject=s;void video.current.play().catch(()=>{});}}).catch(()=>{if(!disposed){setCamera(false);setError(arabic?'الكاميرا غير متاحة أو الإذن مرفوض. استخدم زر التصوير/اختيار صورة أدناه.':'Camera unavailable or permission denied. Use Take / choose photo below.');}});return()=>{disposed=true;stream.current?.getTracks().forEach(x=>x.stop());stream.current=null;};},[camera,arabic]);
 const angles=[t('أمامية','Front'),t('مائلة يسارًا','Left oblique'),t('مائلة يمينًا','Right oblique')];
 const directions=[t('واجه الكاميرا مباشرة. اجعل العينين في مستوى واحد وأظهر الجبهة والذقن.','Face the camera directly. Keep your eyes level and include forehead and chin.'),t('أدر رأسك قليلًا ليظهر الجانب الأيسر من وجهك بوضوح، مع بقاء العينين داخل الصورة.','Turn slightly so the left side of your face is clearly visible, keeping both eyes in frame.'),t('أدر رأسك للجهة الأخرى ليظهر الجانب الأيمن من وجهك بوضوح.','Turn the other way so the right side of your face is clearly visible.')];
 const putPhoto=async(blob:Blob)=>{setBusy(true);setError('');try{const file=await compactPhoto(blob);setPhotos(old=>old.map((p,i)=>i===step?file:p));setSessionId('');setAiConsent(false);setCamera(false);}catch{setError(t('تعذر فتح الصورة. استخدم JPEG أو PNG واضحة.','Cannot open this photo. Use a clear JPEG or PNG.'));}finally{setBusy(false)}};
 const capture=async()=>{const v=video.current;if(!v?.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;canvas.getContext('2d')!.drawImage(v,0,0);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.95));if(blob)await putPhoto(blob)};
 const explain=(code:string)=>({AI_RATE_LIMIT:t('انتظر ٣ دقائق بين التحليلات. الحد اليومي ٥ تحليلات للملف.','Wait 3 minutes between analyses. The record has a daily limit of 5.'),HOME_UPLOAD_RATE_LIMIT:t('وصلت لحد الحفظ اليومي (٣ جلسات).','Daily upload limit reached (3 sessions).'),HOME_STORAGE_LIMIT:t('مساحة جلسات التصوير ممتلئة. تواصل مع العيادة.','Capture storage is full. Contact the clinic.'),OPENAI_KEY_NOT_CONFIGURED:t('خدمة التحليل غير مفعلة حاليًا.','Analysis is not configured yet.'),OPENAI_QUOTA_OR_RATE_LIMIT:t('خدمة التحليل مشغولة أو رصيدها غير متاح. الصور محفوظة؛ تواصل مع العيادة.','Analysis is busy or its quota is unavailable. Photos are saved; contact the clinic.')}[code]||t('تعذر إتمام العملية. حدّث الحالة قبل المحاولة مجددًا.','Could not complete this action. Refresh status before retrying.'));
 const upload=async()=>{setBusy(true);setError('');try{const f=new FormData();photos.forEach(p=>p&&f.append('images',p));f.set('consent','yes');const r=await fetch(endpoint,{method:'POST',body:f});const b=await r.json();if(!r.ok)throw Error(b.error);setSessionId(b.sessionId);setAiConsent(false);await load();}catch(e){setError(explain(e instanceof Error?e.message:''));}finally{setBusy(false)}};
 const analyze=async()=>{setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'generate',sessionId,language:arabic?'ar':'en',consent:true})});const b=await r.json();if(!r.ok)throw Error(b.error);setSelected(b.id);setAiConsent(false);}catch(e){setError(explain(e instanceof Error?e.message:''));}finally{await load();setBusy(false)}};
 const showReport=(r:Report)=>r.report&&<div className="space-y-4"><SkinReportDashboard draft={r.report} patientId={patientId} createdAt={r.created_at} documentId={r.document_id} arabic={arabic} imageEndpoint="/api/patient/skin"/><div className="rounded-2xl bg-slate-50 p-4 text-sm leading-7"><p>{r.report.summary}</p><h4 className="mt-3 font-semibold">{t('حدود التقييم','Assessment limitations')}</h4><p>{r.report.limitations}</p><h4 className="mt-3 font-semibold">{t('نقاط لمراجعة الطبيب','For physician review')}</h4><p>{r.report.reviewPoints}</p></div><details className="rounded-2xl border p-4"><summary className="cursor-pointer font-medium">{t('شرح جميع المؤشرات','All parameter observations')}</summary><div className="mt-3 space-y-3">{r.report.parameters.map(p=><div key={p.id} className="border-b pb-3 text-sm"><strong>{skinParameters[p.id-1][arabic?1:0]} · {p.grade===null?'N/A':`${p.grade*25}%`}</strong><p>{p.observation}</p></div>)}</div></details></div>;
 const activeReport=data?.homeReports.find(r=>r.id===selected)||data?.homeReports.find(r=>r.status==='completed');
 return <div className="mt-6 space-y-6" dir={arabic?'rtl':'ltr'}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-purple-950">{t('تقييم التسجيل والتصوير المنزلي','Baseline & home photography')}</h2><Button variant="outline" disabled={busy||loading} onClick={()=>{setError('');void load()}}><RefreshCw className="size-4"/>{t('تحديث','Refresh')}</Button></div>{error&&<p role="alert" className="rounded-xl bg-amber-50 p-4 text-amber-900">{error}</p>}{loading&&!data&&<p role="status">{t('جارٍ تحميل التقييمات…','Loading assessments…')}</p>}
 {data&&<><section className="rounded-3xl border bg-white p-4 sm:p-6"><h3 className="text-lg font-semibold">{t('تقييم البداية في العيادة','Clinic baseline assessment')}</h3><p className="my-3 text-sm text-slate-600">{t('أول تقرير AI مكتمل في العيادة. التقارير المنزلية لا تستبدله.','The first completed clinic AI report. Home reports do not replace it.')}</p>{data.baseline?<details open><summary className="mb-4 cursor-pointer">{t('عرض تقرير البداية','View baseline report')} · {new Date(data.baseline.created_at).toLocaleDateString(arabic?'ar-JO':'en-GB')}</summary>{showReport(data.baseline)}</details>:<p className="rounded-xl bg-purple-50 p-4">{t('لم يُحفظ تقرير AI أولي في العيادة بعد. الملفات المرفوعة متاحة أدناه.','No clinic AI baseline has been saved yet. Uploaded files appear below.')}</p>}
 <details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-medium">{t('بيانات التسجيل والملفات','Registration data & files')}</summary><p className="my-3 text-xs text-slate-500">{data.registrationSnapshot?t('نسخة البيانات المحفوظة وقت هذا التقييم.','Data snapshot saved with this assessment.'):t('بيانات التسجيل المحفوظة حاليًا؛ قد تتضمن تعديلات لاحقة على جلسة البداية.','Current saved registration data; it may include changes made after the baseline visit.')}</p><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(data.registration).filter(([k,v])=>fields[k]&&String(v)).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">{fields[k][arabic?0:1]}</dt><dd className="mt-1 text-sm">{Array.isArray(v)?v.join('، '):v}</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-3">{data.registrationDocuments.map((d,i)=><a key={d.id} href={`${endpoint}&documentId=${encodeURIComponent(d.id)}`} target="_blank" rel="noreferrer" className="rounded-xl border p-3 text-sm text-purple-800 underline">{d.kind==='report'?t('تقرير مرفوع','Uploaded report'):t('صورة العيادة','Clinic photo')} {i+1} · {d.view_type}</a>)}</div></details></section>
 <section className="rounded-3xl border bg-white p-4 sm:p-6"><div className="flex items-center gap-2"><Camera className="text-purple-700"/><h3 className="text-lg font-semibold">{t('تصوير الوجه في المنزل','Photograph your face at home')}</h3></div><p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm leading-6 text-amber-950">{t('هذا تصوير بإضاءة عادية، وليس بديلًا لأوضاع OBSERV المتخصصة. نتائج AI وصفية وتحتاج مراجعة الطبيب. لا تغيّر علاجك بناءً عليها.','These are normal-light photographs, not specialized OBSERV imaging. AI observations require physician review. Do not change treatment based on them.')}</p>
 <ol className="my-5 list-inside list-decimal space-y-2 text-sm leading-6 text-slate-700"><li>{t('نظّف عدسة الكاميرا، وارفع الشعر عن الوجه، وانزع النظارة والمكياج.','Clean the lens, move hair away from your face, and remove glasses and makeup.')}</li><li>{t('قف أمام ضوء نهار غير مباشر وخلفية بسيطة؛ تجنب الشمس المباشرة والظلال والفلاش.','Face indirect daylight against a plain background. Avoid direct sun, shadows and flash.')}</li><li>{t('اجعل الكاميرا بمستوى العين وعلى بعد نحو ذراع. أوقف فلاتر التجميل والوضع الرأسي.','Keep the camera at eye level, about an arm’s length away. Disable beauty filters and portrait mode.')}</li><li>{t('ثبّت الهاتف وحافظ على تعبير محايد. كرر نفس الإضاءة والمسافة في كل متابعة.','Hold the phone steady with a neutral expression. Repeat the same lighting and distance at follow-up.')}</li></ol>
 {readOnly?<p className="rounded-xl bg-purple-50 p-4">{t('وضع معاينة: التصوير والتحليل المنزلي متاحان من حساب المريض المرتبط بملفه.','Preview mode: home capture and analysis are available from the patient’s linked account.')}</p>:<>
 <div className="mb-4 grid grid-cols-3 gap-2">{angles.map((a,i)=><button type="button" key={a} disabled={busy} onClick={()=>{setStep(i);setCamera(false)}} className={`rounded-xl border p-3 text-sm ${step===i?'border-purple-700 bg-purple-50':'bg-white'}`} aria-pressed={step===i}>{i+1}. {a}{photos[i]&&<Check className="mx-auto mt-1 size-4 text-emerald-700"/>}</button>)}</div><p className="mb-3 font-medium">{directions[step]}</p>
 <div className="relative mx-auto flex aspect-[3/4] max-h-[480px] max-w-sm items-center justify-center overflow-hidden rounded-3xl bg-slate-950 text-white">
 {camera?<video ref={video} autoPlay playsInline muted onLoadedData={()=>setCameraReady(true)} className="h-full w-full object-contain"/>:urls[step]?<img src={urls[step]} alt={angles[step]} className="h-full w-full object-contain"/>:<div className="px-10 text-center text-sm text-slate-300">{t('أظهر الوجه كاملًا من الجبهة إلى الذقن','Include the whole face from forehead to chin')}</div>}
 {(camera||!urls[step])&&<div aria-hidden="true" className="pointer-events-none absolute inset-x-[18%] inset-y-[12%] rounded-[50%] border-2 border-dashed border-white/70"/>}</div>
 <div className="my-4 flex flex-wrap justify-center gap-2">{camera?<><Button disabled={!cameraReady||busy} onClick={()=>void capture()}><Camera/>{t('التقاط الصورة','Capture')}</Button><Button variant="outline" onClick={()=>setCamera(false)}>{t('إغلاق الكاميرا','Close camera')}</Button></>:<Button disabled={busy} onClick={()=>{setError('');if(typeof navigator.mediaDevices?.getUserMedia==='function')setCamera(true);else setError(t('استخدم زر التصوير/اختيار صورة أدناه.','Use Take / choose photo below.'))}}><Camera/>{photos[step]?t('إعادة التصوير','Retake'):t('فتح الكاميرا','Open camera')}</Button>}
 <label className={`cursor-pointer rounded-md border px-4 py-2 text-sm ${busy?'pointer-events-none opacity-50':''}`}>{t('تصوير / اختيار صورة','Take / choose photo')}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/heic,image/heif" capture="user" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void putPhoto(f);e.target.value=''}}/></label>{photos[step]&&step<2&&<Button variant="outline" disabled={busy} onClick={()=>setStep(step+1)}>{t('الصورة التالية','Next view')}</Button>}</div>
 <p className="text-center text-xs text-slate-500">{t('راجع وضوح كل صورة قبل الحفظ. المعاينة ليست فحصًا آليًا لجودة الصورة.','Check each photo is clear before saving. The preview is not an automated quality check.')}</p>
 <label className="my-4 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={storageConsent} onChange={e=>setStorageConsent(e.target.checked)}/>{t('أوافق على حفظ هذه الصور في ملفي لمتابعة البشرة.','I consent to saving these photos in my record for skin follow-up.')}</label><Button disabled={busy||photos.some(p=>!p)||!storageConsent||!!sessionId} onClick={()=>void upload()}><Upload/>{sessionId?t('الصور محفوظة','Photos saved'):busy?t('جارٍ التنفيذ…','Working…'):t('حفظ الصور الثلاث','Save three photos')}</Button>
 <div className="mt-6 rounded-2xl bg-purple-50 p-4"><h4 className="font-semibold">{t('تحليل جلسة تصوير محفوظة','Analyze a saved photo session')}</h4><select aria-label={t('جلسة التصوير','Photo session')} className="my-3 w-full rounded-lg border bg-white p-3" value={sessionId} disabled={busy} onChange={e=>{setSessionId(e.target.value);setAiConsent(false)}}><option value="">{t('اختر جلسة','Choose a session')}</option>{data.sessions.map(s=><option key={s.id} value={s.id}>{new Date(s.created_at).toLocaleString(arabic?'ar-JO':'en-GB')}</option>)}</select>{sessionId&&<div className="mb-3 flex gap-2">{data.sessions.find(s=>s.id===sessionId)?.images.map(s=><img key={s.id} src={`${endpoint}&documentId=${s.id}`} alt={s.angle} className="h-24 w-20 rounded-lg object-cover"/>)}</div>}
 <label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1" checked={aiConsent} disabled={busy} onChange={e=>setAiConsent(e.target.checked)}/>{t('أوافق على إرسال صور هذه الجلسة إلى OpenAI لإعداد تقييم AI مبدئي، وحفظ التقرير في ملفي.','I consent to sending this session’s photos to OpenAI for a preliminary AI assessment and saving the report in my record.')}</label><Button className="mt-4" disabled={busy||!sessionId||!aiConsent||!data.configured} onClick={()=>void analyze()}>{busy?t('جارٍ التنفيذ… قد يستغرق التحليل دقيقة ونصف','Working… analysis may take 90 seconds'):t('تحليل الصور وإعداد التقرير','Analyze photos & create report')}</Button>{!data.configured&&<p className="mt-2 text-sm">{t('خدمة التحليل غير مفعلة حاليًا. يمكنك حفظ الصور.','Analysis is not configured yet. You can save photos.')}</p>}</div></>}
 </section><section className="rounded-3xl border bg-white p-4 sm:p-6"><h3 className="text-lg font-semibold">{t('تقارير المتابعة المنزلية','Home assessment history')}</h3><p className="my-3 text-sm text-slate-600">{t('اختلاف الإضاءة والكاميرا يؤثر على الدرجات. لا نحسب نسبة تحسن آلية بين صور الهاتف وأوضاع جهاز العيادة.','Lighting and camera differences affect scores. No automatic improvement percentage is calculated between phone photos and specialized clinic imaging.')}</p>{!data.homeReports.length&&<p className="text-sm">{t('لا توجد تقارير منزلية بعد.','No home reports yet.')}</p>}<div className="mb-5 flex flex-wrap gap-2">{data.homeReports.map(r=><button type="button" key={r.id} onClick={()=>setSelected(r.id)} className={`rounded-xl border p-3 text-sm ${activeReport?.id===r.id?'bg-purple-50 border-purple-600':''}`}>{new Date(r.created_at).toLocaleString(arabic?'ar-JO':'en-GB')} · {r.status==='completed'?t('مكتمل','Complete'):r.status==='failed'?t('لم يكتمل','Failed'):t('قيد التنفيذ','Pending')}</button>)}</div>{activeReport?.status==='completed'?showReport(activeReport):activeReport&&<p role="status">{activeReport.status==='failed'?t('لم يكتمل التحليل. الصور محفوظة؛ يمكنك إعادة المحاولة من الجلسة أعلاه.','Analysis did not complete. Photos are saved; retry the session above.'):t('التحليل قيد التنفيذ. اضغط تحديث لمعرفة الحالة.','Analysis is pending. Refresh to check its status.')}</p>}</section></>}
 </div>;
}
