"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,FileCheck2,LineChart as LineIcon,Plus,RefreshCw,ShieldCheck,TrendingUp} from "lucide-react";
import {Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {toast} from "sonner";
type Row=Record<string,any>;type Data={report:Row;commercial:Row[];snapshots:Row[];definitions:Row};
const empty:Data={report:{clinical:{},operations:{},commercial:{},readiness:{}},commercial:[],snapshots:[],definitions:{}};
const value=(n:any,suffix="")=>n===null||n===undefined?"—":`${n}${suffix}`;
export default function ReportsCenter({arabic}:{arabic:boolean}){const t=(ar:string,en:string)=>arabic?ar:en;const [data,setData]=useState(empty),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState({eventType:"revenue",source:"direct",campaign:"",amount:""});
 const load=useCallback(async()=>{setLoading(true);const r=await fetch("/api/reports/workspace",{cache:"no-store"});const b=await r.json();if(r.ok)setData(b);else toast.error(b.error||t("تعذر تحميل التقارير","Could not load reports"));setLoading(false)},[arabic]);useEffect(()=>{void load()},[load]);
 const act=async(payload:Row,message:string)=>{const r=await fetch("/api/reports/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){toast.error(b.error||t("تعذر الحفظ","Could not save"));return}toast.success(message);setOpen(false);await load()};const c=data.report.clinical||{},o=data.report.operations||{},biz=data.report.commercial||{},ready=data.report.readiness||{};
 const funnel=useMemo(()=>[[t("مسجلون","Registered"),biz.registered],[t("حضروا التقييم","Assessed"),biz.assessed],[t("بدأوا البرنامج","Program started"),biz.programStarted],[t("أكملوا","Completed"),biz.completed]].map(([name,count])=>({name,count:Number(count||0)})),[biz,arabic]);const evidence=[{name:t("خط أساس معتمد","Approved baseline"),value:Number(ready.baselineComplete||0),color:"#7c3aed"},{name:t("نتائج مكتملة","Completed outcomes"),value:Number(ready.outcomesComplete||0),color:"#f59e0b"}];
 return <section><div className="mb-5 flex flex-wrap items-end justify-between gap-4 rounded-3xl bg-[#17131d] p-6 text-white"><div><div className="flex items-center gap-2 text-sm font-semibold text-purple-300"><BarChart3 className="size-4"/>{t("نظام الإثبات","EVIDENCE SYSTEM")}</div><h2 className="mt-2 text-2xl font-semibold">{t("الأداء السريري والتجاري","Clinical & commercial performance")}</h2><p className="mt-2 max-w-3xl text-sm text-white/60">{t("تعريفات ثابتة، أرقام قابلة للتتبع، ولا تُحتسب القياسات السريرية إلا بعد اعتماد الطبيب.","Fixed definitions, traceable numbers, and clinical measures count only after physician approval.")}</p></div><div className="flex gap-2"><Button variant="outline" className="border-white/20 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={load}><RefreshCw className={loading?"animate-spin":""}/>{t("تحديث","Refresh")}</Button><Button className="bg-amber-400 text-purple-950 hover:bg-amber-300" onClick={()=>act({action:"snapshot"},t("تم حفظ لقطة التقرير","Report snapshot saved"))}><FileCheck2/>{t("حفظ لقطة","Save snapshot")}</Button></div></div>
 <Tabs defaultValue="executive"><TabsList className="h-auto flex-wrap bg-white p-1.5"><TabsTrigger value="executive">{t("الملخص التنفيذي","Executive")}</TabsTrigger><TabsTrigger value="clinical">{t("الإثبات السريري","Clinical evidence")}</TabsTrigger><TabsTrigger value="commercial">{t("الأداء التجاري","Commercial")}</TabsTrigger><TabsTrigger value="governance">{t("الجاهزية والحوكمة","Readiness")}</TabsTrigger></TabsList>
  <TabsContent value="executive" className="mt-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[c.patients,t("مرضى نشطون","Active patients")],[c.adherence,t("الالتزام المسجل","Recorded adherence"),"%"],[biz.programConversion,t("التحويل إلى برنامج","Program conversion"),"%"],[c.satisfaction,t("رضا المريض","Patient satisfaction"),"/5"]].map(([n,l,s])=><Kpi key={l} number={value(n,s as string||"")} label={String(l)}/>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card title={t("مسار البرنامج","Program funnel")}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} margin={{top:10,right:10,left:-20,bottom:20}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:12}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#6b3fa0" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title={t("اكتمال ملف الإثبات","Evidence completeness")}><div className="h-60"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={evidence} dataKey="value" nameKey="name" innerRadius={52} outerRadius={85} paddingAngle={4}>{evidence.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="space-y-2">{evidence.map(x=><div key={x.name} className="flex justify-between text-sm"><span>{x.name}</span><strong>{x.value}%</strong></div>)}</div></Card></div></TabsContent>
  <TabsContent value="clinical" className="mt-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi number={value(c.baselineCoverage,"%")} label={t("تغطية خط الأساس","Baseline coverage")}/><Kpi number={value(c.outcomeCoverage,"%")} label={t("اكتمال النتائج","Outcome completion")}/><Kpi number={value(c.approvedMetricCount)} label={t("قياسات معتمدة","Approved measures")}/><Kpi number={value(c.completedJourneys)} label={t("رحلات مكتملة","Completed journeys")}/></div><Card title={t("قواعد قراءة النتائج","Outcome interpretation rules")} className="mt-5"><div className="grid gap-3 md:grid-cols-3">{[[t("التصوير المعياري","Standardized imaging"),t("نفس الزاوية والإضاءة والمسافة.","Matched angle, light and distance.")],[t("مراجعة الطبيب","Physician review"),t("لا تدخل القياسات غير المعتمدة في التقرير.","Unapproved measures are excluded.")],[t("نتيجة متعددة الأبعاد","Multidimensional outcome"),t("النشاط والاحمرار والتصبغ والملمس والندبات منفصلة.","Activity, redness, pigmentation, texture and scarring stay separate.")]].map(([h,p])=><div key={h} className="rounded-2xl bg-slate-50 p-4"><CheckCircle2 className="size-5 text-emerald-600"/><div className="mt-3 font-medium">{h}</div><p className="mt-1 text-sm leading-6 text-slate-500">{p}</p></div>)}</div></Card></TabsContent>
  <TabsContent value="commercial" className="mt-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="grid flex-1 gap-3 sm:grid-cols-3"><Kpi number={value(biz.assessmentConversion,"%")} label={t("التسجيل ← التقييم","Registration → assessment")}/><Kpi number={value(biz.completionRate,"%")} label={t("اكتمال البرنامج","Program completion")}/><Kpi number={value(biz.roas,"×")} label="ROAS"/></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>{t("تسجيل حركة","Record event")}</Button></DialogTrigger><DialogContent dir={arabic?"rtl":"ltr"}><DialogHeader><DialogTitle>{t("إضافة حركة تجارية","Add commercial event")}</DialogTitle><DialogDescription>{t("تُستخدم للقياس الداخلي فقط ولا تؤثر على القرار السريري.","Used for internal measurement only and never affects clinical decisions.")}</DialogDescription></DialogHeader><div className="space-y-4"><Label>{t("النوع","Type")}</Label><Select value={form.eventType} onValueChange={v=>setForm({...form,eventType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="revenue">Revenue</SelectItem><SelectItem value="marketing_spend">Marketing spend</SelectItem><SelectItem value="referral">Referral</SelectItem><SelectItem value="inquiry">Inquiry</SelectItem></SelectContent></Select><Label>{t("المصدر","Source")}</Label><Input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/><Label>{t("الحملة","Campaign")}</Label><Input value={form.campaign} onChange={e=>setForm({...form,campaign:e.target.value})}/><Label>{t("القيمة بالدينار الأردني","Amount in JOD")}</Label><Input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Button className="w-full" onClick={()=>act({action:"commercial_event",...form},t("تم تسجيل الحركة","Event recorded"))}>{t("حفظ","Save")}</Button></div></DialogContent></Dialog></div><Card title={t("الإيراد والإنفاق المنسوب","Attributed revenue and spend")}><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-5"><div className="text-sm text-emerald-700">{t("الإيراد المسجل","Recorded revenue")}</div><div className="mt-2 text-3xl font-semibold text-emerald-950">{(Number(biz.revenueMinor||0)/100).toFixed(2)} JOD</div></div><div className="rounded-2xl bg-amber-50 p-5"><div className="text-sm text-amber-700">{t("الإنفاق التسويقي","Marketing spend")}</div><div className="mt-2 text-3xl font-semibold text-amber-950">{(Number(biz.spendMinor||0)/100).toFixed(2)} JOD</div></div></div></Card></TabsContent>
  <TabsContent value="governance" className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card title={t("بوابة الجاهزية","Evidence readiness gate")}><div className="space-y-3">{[[ready.consentComplete,t("الموافقة الطبية","Medical consent")],[ready.baselineComplete,t("خط أساس معتمد","Approved baseline")],[ready.outcomesComplete,t("وثيقة نتيجة مكتملة","Completed outcome document")],[c.adherence,t("بيانات التزام مسجلة","Recorded adherence data")]].map(([n,l])=><div key={l} className="flex items-center justify-between rounded-2xl border p-4"><span>{l}</span><Badge className={Number(n)===100?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}>{value(n,"%")}</Badge></div>)}</div><div className="mt-4 rounded-2xl bg-purple-50 p-4"><div className="text-sm text-purple-700">{t("حالات مؤهلة مبدئيًا للقصة","Cases preliminarily eligible for a story")}</div><div className="mt-1 text-2xl font-semibold text-purple-950">{ready.storiesEligible||0}</div></div><p className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm leading-6 text-rose-800">{t("لا يجوز تحويل أي حالة إلى قصة تسويقية إلا مع موافقة تسويق سارية، ونتيجة مكتملة، ومراجعة الطبيب.","No case becomes a marketing story without active marketing consent, a completed outcome, and physician review.")}</p></Card><Card title={t("لقطات التقارير المحفوظة","Saved report snapshots")}><div className="space-y-3">{data.snapshots.map(x=><div key={x.id} className="flex items-center justify-between rounded-2xl border p-4"><div><div className="font-medium">{x.report_type} · v{x.definition_version}</div><div className="text-sm text-slate-500">{x.period_start} → {x.period_end}</div></div><ShieldCheck className="text-purple-600"/></div>)}{!data.snapshots.length&&<div className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-400">{t("لم تُحفظ لقطة بعد","No snapshot saved yet")}</div>}</div></Card></TabsContent>
 </Tabs></section>}
function Kpi({number,label}:{number:string;label:string}){return <div className="rounded-2xl border bg-white p-5"><div className="text-3xl font-semibold text-purple-950">{number}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}
function Card({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border bg-white p-5 ${className}`}><h3 className="mb-4 font-semibold text-purple-950">{title}</h3>{children}</section>}
