"use client";
import {useState} from 'react';
import {skinParameters,descriptiveAverage,type SkinDraft} from '@/lib/skin-assessment';
export default function SkinReportDashboard({draft,patientId,createdAt,documentId,arabic}:{draft:SkinDraft;patientId:string;createdAt:string;documentId:string;arabic:boolean}){
 const t=(ar:string,en:string)=>arabic?ar:en;
 const sources=draft.sources||[{id:documentId,angle:'Unknown',mode:'Unknown'}];
 const [selected,setSelected]=useState(0);
 const source=sources[selected]||sources[0];
 const url=(id:string)=>`/api/intake?patientId=${encodeURIComponent(patientId)}&documentId=${encodeURIComponent(id)}`;
 const average=descriptiveAverage(draft);
 const features=[{id:12,color:'#e8b866'},{id:19,color:'#78c9e4'},{id:7,color:'#ef8989'},{id:27,color:'#bc9be9'}];
 const grade=(value:number|null|undefined)=>value==null?'N/A':`${value*25}%`;
 return <article dir={arabic?'rtl':'ltr'} className="overflow-hidden rounded-3xl border border-[#3e4144] bg-[#181c20] text-[#f1eee8] shadow-xl">
 <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-5 py-5 md:px-7"><div><div className="font-serif text-2xl tracking-wide text-[#e5d2ac]">Derma Glow</div><p className="mt-1 text-[10px] tracking-[0.25em] text-[#b4afa5]">PRECISION CARE</p></div><div className="text-xs leading-6 text-[#b9bdc3]"><p>{t('تقرير تقييم البشرة','Skin assessment report')}</p><time>{new Date(createdAt).toLocaleString(arabic?'ar-JO':'en-GB')}</time><span className="inline-block rounded-full border border-[#e7be77]/40 px-3 text-[#e7be77]">{t('مسودة AI · مراجعة الطبيب مطلوبة','AI draft · Physician review required')}</span></div></header>
 <div className="grid gap-5 p-4 md:p-7 xl:grid-cols-[minmax(0,1.2fr)_minmax(210px,.7fr)_minmax(240px,.9fr)]">
 <section className="min-w-0"><h3 className="text-xl font-medium">{t('ملف البشرة البصري','Skin intelligence overview')}</h3><p className="mb-4 mt-2 text-xs text-[#aeb4bb]">{source.angle} · {source.mode} · {t('الصورة الأصلية','Original image')}</p><a href={url(source.id)} target="_blank" rel="noreferrer" className="block overflow-hidden rounded-2xl bg-[#101315]"><img className="h-[360px] w-full object-contain md:h-[460px]" src={url(source.id)} alt={t('الصورة المستخدمة في التقييم','Assessment source image')}/></a><div className="mt-3 flex gap-2 overflow-x-auto pb-2">{sources.map((s,i)=><button type="button" key={s.id} onClick={()=>setSelected(i)} aria-label={`${t('الصورة','Image')} ${i+1}`} aria-pressed={s.id===source.id} className={`shrink-0 rounded-lg border-2 p-1 ${s.id===source.id?'border-[#e7be77]':'border-transparent'}`}><img loading="lazy" alt="" src={url(s.id)} className="h-14 w-11 rounded object-cover"/><span className="text-[10px]">{i+1}</span></button>)}</div></section>
 <section className="grid content-start gap-3"><h4 className="mb-1 text-sm text-[#b9bdc3]">{t('مؤشرات مختارة','Selected observations')}</h4>{features.map(f=>{const p=draft.parameters.find(p=>p.id===f.id);return <div key={f.id} className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/5 to-transparent p-4"><div className="flex items-center gap-2"><span style={{background:f.color}} className="h-2 w-2 rounded-full"/><h5 className="text-sm">{skinParameters[f.id-1][arabic?1:0]}</h5></div><div className="my-3 flex items-center justify-between"><strong className="text-2xl font-light" style={{color:f.color}}>{grade(p?.grade)}</strong><span className="text-xs text-[#b9bdc3]">{t('درجة وصفية','Visual grade')}</span></div><div className="h-1 overflow-hidden rounded bg-white/10"><div style={{width:`${(p?.grade??0)*25}%`,background:f.color}} className="h-full rounded"/></div></div>})}
 <div className="flex items-center gap-3 rounded-2xl border border-[#e7be77]/25 p-4"><div className="relative h-20 w-20 shrink-0"><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90" aria-hidden="true"><circle cx="50" cy="50" r="43" fill="none" stroke="#383d42" strokeWidth="5"/><circle cx="50" cy="50" r="43" fill="none" stroke="#e7be77" strokeWidth="5" strokeLinecap="round" strokeDasharray={`${(average.normalized??0)*2.702} 270.2`}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl font-light">{average.normalized===null?'N/A':average.normalized.toFixed(1)}</strong><span className="text-[10px] text-[#b9bdc3]">{average.normalized===null?'':'%'}</span></div></div><div><h5 className="text-sm text-[#e7be77]">{t('المتوسط الوصفي','Descriptive average')}</h5><p className="mt-1 text-xs text-[#b9bdc3]">{average.count}/36 {t('بندًا مقيمًا','items graded')}</p></div></div></section>
 <aside className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><h4 className="text-lg">{t('تفاصيل الدرجات','Observation scores')}</h4><p className="mb-5 mt-1 text-xs text-[#aeb4bb]">{t('نسبة وصفية · N/A غير قابل للتقييم','Descriptive percentage · N/A not assessable')}</p><div className="max-h-[530px] space-y-4 overflow-y-auto pe-2">{draft.parameters.map(p=><div key={p.id}><div className="mb-2 flex items-start justify-between gap-3 text-xs"><span className="text-[#ced1d4]">{skinParameters[p.id-1][arabic?1:0]}</span><span className="shrink-0 text-[#e7be77]">{grade(p.grade)}</span></div><div className="h-[3px] rounded bg-white/10"><div className="h-full rounded bg-[#d9bd89]" style={{width:`${(p.grade??0)*25}%`}}/></div></div>)}</div></aside>
 </div><footer className="border-t border-white/10 px-5 py-4 text-xs leading-6 text-[#b9bdc3]"><p>{t('٠٪ غير ظاهر · ٢٥٪ طفيف · ٥٠٪ خفيف · ٧٥٪ متوسط · ١٠٠٪ بارز. نسب وصفية وليست مساحة إصابة أو احتمال تشخيص.','0% not visible · 25% slight · 50% mild · 75% moderate · 100% marked. Visual grades, not affected area or diagnostic probability.')}</p><p>{t('المتوسط حسابي وغير معتمد طبيًا؛ لا يقيس صحة البشرة ولا يحدد العلاج. الصور دون خرائط أو قياسات موضعية مولدة.','The average is arithmetic and clinically unvalidated; it does not measure skin health or select treatment. Images are shown without generated lesion maps or localized measurements.')}</p></footer>
 </article>;
}
