"use client";
import SkinReportDashboard from "./skin-report-dashboard";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {skinParameters,descriptiveAverage,imageAngles,imageModes,type SkinDraft} from '@/lib/skin-assessment';
type Report={id:string;document_id:string;status:string;report:SkinDraft|null;created_at:string;model:string;error_code:string|null;comments:{comment:string;created_by:string;created_at:string}[]};
const errors:Record<string,[string,string]>={IMAGE_SET_TOO_LARGE:['إجمالي الصور أكبر من ٨ ميجابايت. اختر مجموعة أصغر.','Images exceed 8 MB total. Select a smaller group.'],INVALID_IMAGE_SELECTION:['اختر من صورة إلى ٣٠ صورة وحدد الزاوية والوضع من القوائم.','Select 1–30 images and use the provided angle/mode options.'],OPENAI_KEY_NOT_CONFIGURED:['مفتاح OpenAI غير موجود في إعدادات الخادم.','The OpenAI key is not configured on the server.'],OPENAI_AUTH_ERROR:['رفض OpenAI المفتاح. راجع المفتاح وصلاحياته.','OpenAI rejected the key. Check the key and its permissions.'],OPENAI_QUOTA_OR_RATE_LIMIT:['راجع رصيد وفوترة OpenAI أو حاول لاحقًا بسبب حد الطلبات.','Check OpenAI API billing/credit, or retry later if rate-limited.'],AI_RATE_LIMIT:['انتظر ٣ دقائق بين المحاولات. الحد ٥ محاولات للمريض و٥٠ للعيادة/الحساب يوميًا (UTC).','Wait 3 minutes between attempts. Limits: 5 per patient and 50 per tenant daily (UTC).'],AI_TIMEOUT:['انتهت مهلة الطلب. لم يتم إنشاء تقرير.','The request timed out. No report was generated.'],SAVE_IMAGING_CONSENT_FIRST:['احفظ موافقة حفظ الصور أولًا.','Save imaging consent first.'],IMAGE_NOT_FOUND:['الصورة غير موجودة. حدّث الملف.','Image unavailable. Refresh the record.']};
export default function SkinAIAssessment({patientId,images,arabic}:{patientId:string;images:{id:string;filename:string;view_type:string}[];arabic:boolean}){
 const t=(a:string,b:string)=>arabic?a:b;
 const [choices,setChoices]=useState<Record<string,{angle:string;mode:string}>>({});
 const chosen=images.filter(d=>choices[d.id]).map(d=>({id:d.id,...choices[d.id]}));
 const choiceKey=JSON.stringify(chosen);
 const endpoint=`/api/intake/ai?patientId=${encodeURIComponent(patientId)}`;
 const [reports,setReports]=useState<Report[]>([]),[configured,setConfigured]=useState(false),[canComment,setCanComment]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[comment,setComment]=useState('');
 const explain=(code:string)=>errors[code]?.[arabic?0:1]||t('تعذر إتمام العملية.','Could not complete the operation.')+` (${code})`;
 const load=async()=>{const r=await fetch(endpoint,{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error||'AI_STORAGE_UNAVAILABLE');setReports(b.reports);setConfigured(b.configured);setCanComment(b.canComment);};
 useEffect(()=>{let active=true;setReports([]);setConfigured(false);setCanComment(false);setSelected('');setComment('');setConsent(false);setError('');fetch(endpoint,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);if(active){setReports(b.reports);setConfigured(b.configured);setCanComment(b.canComment);}}).catch(e=>{if(active)setError(explain(e.message));});return()=>{active=false;};},[patientId]);
 useEffect(()=>{setConsent(false);},[choiceKey]);
 const current=reports.find(r=>r.id===selected)||reports[0];
 const draft=current?.report;const avg=draft?descriptiveAverage(draft):null;
 const send=async(body:unknown)=>{setBusy(true);setError('');setNotice('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error||'AI_REQUEST_FAILED');if(b.id)setSelected(b.id);setComment('');await load();setNotice(t('تم الحفظ. التقرير مسودة غير معتمدة.','Saved. The report remains an unapproved draft.'));}catch(e){setError(explain(e instanceof Error?e.message:'AI_REQUEST_FAILED'));}finally{setBusy(false);}};
 return <section className="space-y-4 rounded-2xl border border-purple-200 p-4" dir={arabic?'rtl':'ltr'}>
 <h3 className="text-lg font-semibold">{t('تقييم بصري بمساعدة الذكاء الاصطناعي','AI-assisted visual assessment')}</h3>
 <p className="text-sm text-slate-600">{t('مسودة للمراجعة الطبية، لا تشخيص ولا اختيار تلقائي للعلاج. يُحلل الصور المختارة معًا؛ التقرير المرفوع منفصل ولا تُستخرج درجاته هنا.','Draft for physician review, not a diagnosis or automatic treatment selection. Analyzes the selected images together; the uploaded report remains separate and its scores are not extracted here.')}</p>
 {!configured&&<p className="text-sm text-amber-800">{t('التحليل غير متاح حتى إعداد مفتاح OpenAI على الخادم.','Analysis is unavailable until the OpenAI key is configured on the server.')}</p>}
 <p className="text-sm">{t('اختر صور نفس المريض ونفس جلسة التصوير. حتى ٣٠ صورة، وإجمالي ٨ ميجابايت للمجموعة. لا تخمّن وضع الإضاءة: اختر Unknown إذا لم تعرفه.','Select images from the same patient and session. Up to 30 images, 8 MB total per group. Choose Unknown when the lighting mode is not known.')}</p>
 <div className="flex gap-2"><Button type="button" variant="outline" disabled={busy||images.length>30} onClick={()=>setChoices(Object.fromEntries(images.map(d=>[d.id,{angle:'Unknown',mode:'Unknown'}])))}>{t('اختيار الكل','Select all')}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setChoices({})}>{t('إلغاء الاختيار','Clear selection')}</Button></div>
 <div className="max-h-96 space-y-2 overflow-y-auto">{images.map((d,i)=><div key={d.id} className="flex flex-wrap items-center gap-2 rounded-xl border p-2"><label className="flex flex-1 items-center gap-2"><input type="checkbox" disabled={busy} checked={!!choices[d.id]} onChange={e=>setChoices(old=>{const next={...old};if(e.target.checked)next[d.id]={angle:'Unknown',mode:'Unknown'};else delete next[d.id];return next;})}/><img alt="" loading="lazy" className="h-16 w-12 object-cover" src={`/api/intake?patientId=${encodeURIComponent(patientId)}&documentId=${encodeURIComponent(d.id)}`}/><span className="break-all text-xs">{i+1}. {d.filename}</span></label>{choices[d.id]&&<>{(['angle','mode'] as const).map(field=><label key={field} className="grid text-xs">{field==='angle'?t('الزاوية','Angle'):t('وضع التصوير','Imaging mode')}<select disabled={busy} className="rounded border p-2" value={choices[d.id][field]} onChange={e=>setChoices(old=>({...old,[d.id]:{...old[d.id],[field]:e.target.value}}))}>{(field==='angle'?imageAngles:imageModes).map(v=><option key={v}>{v}</option>)}</select></label>)}</>}</div>)}</div>
 <p>{chosen.length}/30 {t('صورة مختارة','images selected')}</p>
 <label className="flex items-start gap-2 rounded-xl bg-amber-50 p-3 text-sm"><input type="checkbox" checked={consent} disabled={busy||!chosen.length||chosen.length>30} onChange={e=>setConsent(e.target.checked)}/>{t('أؤكد الحصول على موافقة المريض لإرسال هذه الصور إلى OpenAI لمعالجتها وإعداد مسودة تقييم. قد تتضمن الصورة وجهه. تُطبق سياسة معالجة البيانات لدى OpenAI وتكلفة استخدام API.','I confirm patient consent to send these images, which may include their face, to OpenAI for processing and a draft assessment. OpenAI data handling policies and API usage charges apply.')}</label>
 <Button type="button" disabled={busy||!configured||!chosen.length||chosen.length>30||!consent} onClick={()=>{if(window.confirm(t('إرسال مجموعة الصور المختارة إلى OpenAI الآن؟','Send all selected images to OpenAI now?')))void send({action:'generate',images:chosen,language:arabic?'ar':'en',consent:true});}}>{busy?t('جارٍ التنفيذ…','Processing…'):t('إنشاء تقرير موحّد للصور المختارة','Generate combined image assessment')}</Button>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-green-800">{notice}</p>}
 <Button type="button" variant="outline" disabled={busy} onClick={()=>void load().catch(e=>setError(explain(e.message)))}>{t('تحديث النتائج','Refresh results')}</Button>
 {!!reports.length&&<label className="grid gap-2">{t('سجل التقييمات - آخر ١٠ محاولات','Assessment history - last 10 attempts')}<select className="rounded-xl border p-2" disabled={busy} value={current?.id||''} onChange={e=>{setSelected(e.target.value);setComment('');}}>{reports.map(r=><option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleString()} - {r.status}</option>)}</select></label>}
 {current&&<p className="text-xs text-slate-500">{new Date(current.created_at).toLocaleString()} · {current.model} · {t('مسودة غير معتمدة','Unapproved draft')}</p>}
 {current?.status==='pending'&&<p>{t('الطلب قيد التنفيذ أو انقطع. حدّث النتائج؛ إن لم يكتمل يمكنك المحاولة بعد ٣ دقائق.','Request pending or interrupted. Refresh results; if unfinished, retry after 3 minutes.')}</p>}
 {current?.status==='failed'&&<p className="text-red-700">{explain(current.error_code||'AI_REQUEST_FAILED')}</p>}
 {draft&&<>
 <SkinReportDashboard key={current.id} draft={draft} patientId={patientId} createdAt={current.created_at} documentId={current.document_id} arabic={arabic}/>
 <p className="whitespace-pre-wrap">{draft.summary}</p><p className="whitespace-pre-wrap text-sm text-amber-900">{draft.limitations}</p>
 <p className="text-sm">{t('الدرجات من ٤: ٠ غير ظاهر في منطقة قابلة للتقييم؛ ١ طفيف؛ ٢ خفيف؛ ٣ متوسط؛ ٤ بارز. N/A = غير قابل للتقييم، وليس صفرًا.','Grades out of 4: 0 not visible in an assessable area; 1 slight; 2 mild; 3 moderate; 4 marked. N/A means not assessable, not zero.')}</p>
 {avg&&<div className="rounded-xl bg-purple-50 p-3"><strong>{t('المتوسط الوصفي: ','Descriptive average: ')}{avg.mean===null?'N/A':`${avg.mean.toFixed(2)}/4 (${avg.normalized!.toFixed(1)}/100)`}</strong><p className="text-sm">{avg.count}/36 {t('بندًا قابلًا للتقييم.','items graded.')} {avg.count>0&&`${avg.sum} / (${avg.count} × 4) × 100`}</p><p className="text-sm">{t('متوسط حسابي غير معتمد طبيًا؛ بعض البنود متداخلة. لا يقيس صحة البشرة أو شدة المرض ولا يُستخدم للمقارنة بين الزيارات أو لاختيار العلاج.','Unvalidated arithmetic average; some items overlap. Not a skin-health or disease-severity score, and not for visit comparisons or treatment selection.')}</p></div>}
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-start">{t('البند','Parameter')}</th><th className="p-2">{t('الدرجة / ٤','Grade / 4')}</th><th className="p-2 text-start">{t('الملاحظة','Observation')}</th></tr></thead><tbody>{[...draft.parameters].sort((a,b)=>a.id-b.id).map(p=><tr key={p.id} className="border-b"><td className="p-2">{p.id}. {skinParameters[p.id-1][arabic?1:0]}</td><td className="p-2 text-center">{p.grade===null?'N/A':`${p.grade}/4`}</td><td className="p-2">{p.observation}{!!p.sourceImages?.length&&<small className="block text-purple-700">{t('الصور الداعمة: ','Supporting images: ')}{p.sourceImages.join(', ')}</small>}</td></tr>)}</tbody></table></div>
 <h4 className="font-semibold">{t('نقاط للمراجعة الطبية','Points for physician review')}</h4><p className="whitespace-pre-wrap">{draft.reviewPoints}</p>
 <h4 className="font-semibold">{t('صور مصدر التقرير','Report source images')}</h4><div className="flex flex-wrap gap-3">{(draft.sources||[{id:current.document_id,angle:'Unknown',mode:'Unknown'}]).map((source,i)=><a key={source.id} className="w-28 text-xs underline" target="_blank" rel="noreferrer" href={`/api/intake?patientId=${encodeURIComponent(patientId)}&documentId=${encodeURIComponent(source.id)}`}><img loading="lazy" alt={`${i+1}`} className="h-28 w-24 object-contain" src={`/api/intake?patientId=${encodeURIComponent(patientId)}&documentId=${encodeURIComponent(source.id)}`}/>{i+1}. {source.angle} · {source.mode}</a>)}</div><p className="text-xs">{t('قد لا تتوفر الصورة إذا حُذفت لاحقًا.','An image may be unavailable if subsequently deleted.')}</p>
 <h4 className="font-semibold">{t('تعليقات الطبيب','Physician comments')}</h4>{current.comments.map((c,i)=><div className="rounded-xl bg-slate-50 p-3" key={i}><p className="whitespace-pre-wrap">{c.comment}</p><small>{c.created_by} · {new Date(c.created_at).toLocaleString()}</small></div>)}
 {canComment?<><textarea aria-label={t('تعليق الطبيب','Physician comment')} className="min-h-28 w-full rounded-xl border p-3" maxLength={5000} disabled={busy} value={comment} onChange={e=>setComment(e.target.value)} placeholder={t('أضف تعليقاتك أو تصحيحاتك؛ تحفظ منفصلة عن مسودة AI.','Add comments or corrections; saved separately from the AI draft.')}/><Button type="button" disabled={busy||!comment.trim()} onClick={()=>void send({action:'comment',reportId:current.id,comment})}>{t('حفظ تعليق الطبيب','Save physician comment')}</Button></>:<p className="text-sm text-slate-500">{t('إضافة التعليقات متاحة للطبيب أو المدير الطبي أو المدير الأعلى.','Comments can be added by a physician, medical director or super admin.')}</p>}
 </>}
 </section>;
}
