const rate=(n,d)=>d?Math.round(n/d*100):null;
export function buildReport({patients=[],intakes=[],journeys=[],tasks=[],appointments=[],metrics=[],outcomes=[],reportedOutcomes=[],messages=[],commercial=[],marketingConsents=[]}){
 const patientCount=patients.length,completedTasks=tasks.filter(x=>x.status==="done").length,recordedTasks=tasks.filter(x=>["done","skipped"].includes(x.status)).length;
 const assessmentPatients=new Set(intakes.filter(x=>x.checked_in_at).map(x=>x.patient_id)).size,programPatients=new Set(journeys.filter(x=>!["REGISTERED","ASSESSMENT_STARTED","BASELINE_CAPTURED"].includes(x.current_state)).map(x=>x.patient_id)).size,completedPatients=new Set(journeys.filter(x=>x.current_state==="COMPLETED").map(x=>x.patient_id)).size;
 const baselinePatients=new Set(metrics.filter(x=>x.review_state==="approved").map(x=>x.patient_id)).size,outcomePatients=new Set(outcomes.filter(x=>x.completed_at).map(x=>x.patient_id)).size;
 const attended=appointments.filter(x=>["completed","attended"].includes(x.status)).length,noShows=appointments.filter(x=>x.status==="no_show").length;
 const responseMinutes=messages.filter(x=>x.sender_role==="care_team").map(m=>{const prior=messages.filter(p=>p.thread_id===m.thread_id&&p.sender_role==="patient"&&new Date(p.sent_at)<new Date(m.sent_at)).at(-1);return prior?(new Date(m.sent_at)-new Date(prior.sent_at))/60000:null}).filter(x=>x!==null);
 const revenue=commercial.filter(x=>x.event_type==="revenue").reduce((s,x)=>s+Number(x.amount_minor||0),0),spend=commercial.filter(x=>x.event_type==="marketing_spend").reduce((s,x)=>s+Number(x.amount_minor||0),0);
 const ratings=reportedOutcomes.map(x=>Number(x.rating)).filter(Number.isFinite);
 const consented=new Set(marketingConsents.filter(x=>Boolean(x.granted)&&!x.withdrawn_at).map(x=>x.patient_id));
 return {clinical:{patients:patientCount,baselineCoverage:rate(baselinePatients,patientCount),outcomeCoverage:rate(outcomePatients,patientCount),adherence:rate(completedTasks,recordedTasks),completedJourneys:completedPatients,satisfaction:ratings.length?Math.round(ratings.reduce((a,b)=>a+b,0)/ratings.length*10)/10:null,approvedMetricCount:metrics.filter(x=>x.review_state==="approved").length},operations:{assessmentAttendance:rate(attended,attended+noShows),noShows,medianResponseMinutes:responseMinutes.length?responseMinutes.sort((a,b)=>a-b)[Math.floor(responseMinutes.length/2)]:null},commercial:{registered:patientCount,assessed:assessmentPatients,programStarted:programPatients,completed:completedPatients,assessmentConversion:rate(assessmentPatients,patientCount),programConversion:rate(programPatients,assessmentPatients),completionRate:rate(completedPatients,programPatients),revenueMinor:revenue,spendMinor:spend,roas:spend?Math.round(revenue/spend*100)/100:null},readiness:{baselineComplete:rate(baselinePatients,patientCount),outcomesComplete:rate(outcomePatients,patientCount),consentComplete:rate(new Set(intakes.filter(x=>x.medical_consent_status==="signed").map(x=>x.patient_id)).size,patientCount),storiesEligible:outcomes.filter(o=>o.completed_at&&consented.has(o.patient_id)).length}};
}
