import {NextResponse} from "next/server";
import {operationalRole,requireOperationalContext} from "@/lib/server-access";
import {automationCandidates} from "@/lib/automation-engine.mjs";
export const dynamic="force-dynamic";
type Body={action:string;[key:string]:unknown};
export async function POST(request:Request){const ctx=await requireOperationalContext();if("error" in ctx)return NextResponse.json({error:ctx.error},{status:ctx.status});if(!operationalRole(ctx.roles))return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json().catch(()=>null) as Body|null;if(!body?.action)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const {db,tenantId,clinicId,user}=ctx,now=new Date().toISOString();let entityId="";
 try{
  if(body.action==="staff_send"){const thread=await db.prepare("SELECT * FROM message_threads WHERE id=? AND tenant_id=?").bind(body.threadId,tenantId).first<Record<string,unknown>>();if(!thread)throw new Error("THREAD_NOT_FOUND");const message=String(body.message||"").trim();if(!message)throw new Error("MESSAGE_REQUIRED");entityId=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO patient_messages (id,tenant_id,thread_id,patient_id,sender_id,sender_role,body,delivery_status,sent_at,created_at,updated_at) VALUES (?,?,?,?,?,'care_team',?,'delivered',?,?,?)").bind(entityId,tenantId,thread.id,thread.patient_id,user.id,message,now,now,now),db.prepare("UPDATE message_threads SET last_message_at=?,updated_at=? WHERE id=?").bind(now,now,thread.id),db.prepare("UPDATE patient_messages SET read_at=? WHERE thread_id=? AND sender_role='patient' AND read_at IS NULL").bind(now,thread.id)]);}
  else if(body.action==="rule_toggle"){entityId=String(body.ruleId);await db.prepare("UPDATE automation_rules SET enabled=?,updated_at=? WHERE id=? AND tenant_id=?").bind(body.enabled?1:0,now,entityId,tenantId).run();}
  else if(body.action==="task_resolve"){entityId=String(body.taskId);await db.prepare("UPDATE care_tasks SET status='resolved',resolved_by=?,resolved_at=?,updated_at=? WHERE id=? AND tenant_id=?").bind(user.id,now,now,entityId,tenantId).run();}
  else if(body.action==="run_automations"){
   const [appointments,sessions,tasks,rules]=await Promise.all([db.prepare("SELECT a.*,pp.preferred_language FROM appointments a LEFT JOIN patient_profiles pp ON pp.patient_id=a.patient_id WHERE a.tenant_id=? AND a.status IN ('scheduled','confirmed')").bind(tenantId).all(),db.prepare("SELECT ts.*,pp.preferred_language FROM treatment_sessions ts LEFT JOIN patient_profiles pp ON pp.patient_id=ts.patient_id WHERE ts.tenant_id=?").bind(tenantId).all(),db.prepare("SELECT rt.*,pp.preferred_language FROM routine_tasks rt LEFT JOIN patient_profiles pp ON pp.patient_id=rt.patient_id WHERE rt.tenant_id=?").bind(tenantId).all(),db.prepare("SELECT * FROM automation_rules WHERE tenant_id=? AND enabled=1").bind(tenantId).all()]);const enabled=new Set(rules.results.map((x:any)=>x.key));const candidates=automationCandidates({now,appointments:appointments.results,sessions:sessions.results,tasks:tasks.results}).filter(x=>enabled.has(x.ruleKey));let queued=0;
   for(const x of candidates){const id=crypto.randomUUID();try{await db.prepare("INSERT INTO notification_outbox (id,tenant_id,patient_id,rule_key,channel,body,status,scheduled_for,sent_at,dedupe_key,created_at,updated_at) VALUES (?,?,?,?,'in_app',?,'delivered',?,?,?,?,?,?)").bind(id,tenantId,x.patientId,x.ruleKey,x.body,x.scheduledFor,now,x.dedupeKey,now,now).run();queued++;if(x.ruleKey==="missed_routine")await db.prepare("INSERT INTO care_tasks (id,tenant_id,clinic_id,patient_id,task_type,title,status,priority,owner_role,due_at,source_entity_type,source_entity_id,created_at,updated_at) VALUES (?,?,?,?,?,'Follow up missed routine','open','normal','journey_coordinator',?,'routine_task',?,?,?)").bind(crypto.randomUUID(),tenantId,clinicId,x.patientId,x.ruleKey,now,x.sourceId,now,now).run()}catch(e){if(!String(e).includes("UNIQUE"))throw e}}
   entityId=`automation_run:${now}`;return NextResponse.json({ok:true,queued});
  } else throw new Error("UNKNOWN_ACTION");
  await db.prepare("INSERT INTO audit_logs (id,tenant_id,actor_id,entity_type,entity_id,action,after_json,occurred_at,created_at,updated_at) VALUES (?,?,?,'communications',?,?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,user.id,entityId,body.action,JSON.stringify(body),now,now,now).run();return NextResponse.json({ok:true});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"ACTION_REJECTED"},{status:409})}}
