import {NextResponse} from "next/server";
import {requireOperationalContext} from "@/lib/server-access";
import {validatePatientAction} from "@/lib/patient-workflow.mjs";
export const dynamic="force-dynamic";
type Body={action:string;patientId?:string;[key:string]:unknown};

export async function POST(request:Request){
 const ctx=await requireOperationalContext();if("error" in ctx)return NextResponse.json({error:ctx.error},{status:ctx.status});const body=await request.json().catch(()=>null) as Body|null;
 try{validatePatientAction(body)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"INVALID_REQUEST"},{status:400})}
 const {db,tenantId,user,roles}=ctx,now=new Date().toISOString(),isPrivileged=roles.some(r=>["super_admin","clinic_admin"].includes(r));
 const patient=isPrivileged&&body?.patientId?await db.prepare("SELECT * FROM patients WHERE id=? AND tenant_id=?").bind(body.patientId,tenantId).first<Record<string,unknown>>():await db.prepare("SELECT * FROM patients WHERE profile_id=? AND tenant_id=?").bind(user.id,tenantId).first<Record<string,unknown>>();
 if(!patient)return NextResponse.json({error:"PATIENT_NOT_FOUND"},{status:404});const patientId=String(patient.id),clinicId=String(patient.clinic_id),action=body!.action;let entityId=patientId;
 try{
  if(action==="task_complete"||action==="task_skip"){const status=action==="task_complete"?"done":"skipped";const result=await db.prepare("UPDATE routine_tasks SET status=?,completed_at=?,skip_reason=?,updated_at=? WHERE id=? AND patient_id=? AND tenant_id=? AND status='pending'").bind(status,status==="done"?now:null,status==="skipped"?String(body!.reason):null,now,body!.taskId,patientId,tenantId).run();if(!result.meta.changes)throw new Error("TASK_NOT_AVAILABLE");entityId=String(body!.taskId)}
  else if(action==="request_reschedule"){const appointment=await db.prepare("SELECT id FROM appointments WHERE id=? AND patient_id=? AND tenant_id=?").bind(body!.appointmentId,patientId,tenantId).first();if(!appointment)throw new Error("APPOINTMENT_NOT_FOUND");entityId=crypto.randomUUID();await db.prepare("INSERT INTO reschedule_requests (id,tenant_id,clinic_id,appointment_id,patient_id,preferred_starts_at,reason,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?)").bind(entityId,tenantId,clinicId,body!.appointmentId,patientId,body!.preferredStartsAt,body!.reason,now,now).run()}
  else if(action==="send_message"){let threadId=String(body!.threadId||"");if(!threadId){threadId=crypto.randomUUID();await db.prepare("INSERT INTO message_threads (id,tenant_id,patient_id,category,status,last_message_at,created_at,updated_at) VALUES (?,?,?,?,'open',?,?,?)").bind(threadId,tenantId,patientId,String(body!.category||"care_question"),now,now,now).run()}entityId=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO patient_messages (id,tenant_id,thread_id,patient_id,sender_id,sender_role,body,delivery_status,sent_at,created_at,updated_at) VALUES (?,?,?,?,?,'patient',?,'sent',?,?,?)").bind(entityId,tenantId,threadId,patientId,user.id,String(body!.message).trim(),now,now,now),db.prepare("UPDATE message_threads SET last_message_at=?,updated_at=? WHERE id=? AND patient_id=?").bind(now,now,threadId,patientId)])}
  else if(action==="save_preferences"){await db.prepare("INSERT INTO notification_preferences (id,tenant_id,patient_id,morning_time,evening_time,timezone,medication_opt_in,appointment_opt_in,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(patient_id) DO UPDATE SET morning_time=excluded.morning_time,evening_time=excluded.evening_time,timezone=excluded.timezone,medication_opt_in=excluded.medication_opt_in,appointment_opt_in=excluded.appointment_opt_in,updated_at=excluded.updated_at").bind(crypto.randomUUID(),tenantId,patientId,body!.morningTime||"08:00",body!.eveningTime||"20:00",body!.timezone||"Asia/Amman",body!.medicationOptIn?1:0,body!.appointmentOptIn?1:0,now,now).run()}
  else if(action==="submit_checkin"){entityId=crypto.randomUUID();const redFlag=Boolean(body!.redFlag);await db.prepare("INSERT INTO home_assessments (id,tenant_id,patient_id,program_id,rating,symptoms_json,notes,patient_red_flag,submitted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(entityId,tenantId,patientId,body!.programId||null,Number(body!.rating),JSON.stringify(body!.symptoms||[]),body!.notes||null,redFlag?1:0,now,now,now).run();if(redFlag)await db.prepare("INSERT INTO alerts (id,tenant_id,patient_id,severity,status,rule_key,due_at,created_at,updated_at) VALUES (?, ?,?,'high','open','patient_reported_red_flag',?,?,?)").bind(crypto.randomUUID(),tenantId,patientId,now,now,now).run()}
  else if(action==="appointment_confirm"||action==="appointment_cancel"){const status=action==="appointment_confirm"?"confirmed":"cancelled";await db.prepare("UPDATE appointments SET status=?,updated_at=? WHERE id=? AND patient_id=? AND tenant_id=?").bind(status,now,body!.appointmentId,patientId,tenantId).run();entityId=String(body!.appointmentId)}
  else if(action==="marketing_consent"){entityId=crypto.randomUUID();const granted=Boolean(body!.granted);await db.prepare("INSERT INTO marketing_consents (id,tenant_id,patient_id,granted,version,recorded_at,withdrawn_at,created_at,updated_at) VALUES (?,?,?,?,'1.0',?,?,?,?)").bind(entityId,tenantId,patientId,granted?1:0,now,granted?null:now,now,now).run()}
  else if(action==="submit_outcome"){entityId=crypto.randomUUID();await db.prepare("INSERT INTO patient_reported_outcomes (id,tenant_id,patient_id,program_id,outcome_type,rating,comment,submitted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(entityId,tenantId,patientId,body!.programId||null,"satisfaction",Number(body!.rating),body!.comment||null,now,now,now).run()}
  await db.prepare("INSERT INTO audit_logs (id,tenant_id,actor_id,entity_type,entity_id,action,after_json,occurred_at,created_at,updated_at) VALUES (?,?,?,'patient_portal',?,?,?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,user.id,entityId,action,JSON.stringify({...body,patientId}),now,now,now).run();
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"ACTION_REJECTED"},{status:409})}
 return NextResponse.json({ok:true,entityId});
}
